### ISSUE TITLE
Unable to join Slack

### ISSUE THREAD

**Issue by azhikai** [nus-cs2103-AY1819S1/forum#1]
The sign-in/registration (as illustrated) requires us to possess a **@nus.edu.sg** domain which students don't -- ours are either **@u.nus.edu** or **@comp.nus.edu.sg**. 

![image](https://user-images.githubusercontent.com/7473075/44087924-e7f781e4-9ff3-11e8-8c9c-2c17c6ff109c.png)

![image](https://user-images.githubusercontent.com/7473075/44087955-047d8804-9ff4-11e8-9072-59457fda017a.png)

**Comment by damithc** [comment]
Thanks for the bug report @AZhiKai I've added `u.nus.edu.sg` and `comp.nus.edu.sg` to the list. Please try again.

**Comment by azhikai** [comment]
Hi Prof @damithc, 

There's just one small bug: it should be `u.nus.edu` instead of `u.nus.edu.sg`. 

Other than that, I've successfully registered into the Slack, so all's good. Issue can be closed.

**Comment by damithc** [comment]
> There's just one small bug: it should be u.nus.edu instead of u.nus.edu.sg.

Oops. Fixed. Thanks for spotting it.
