### ISSUE TITLE
User Preferences 

### ISSUE THREAD

**Issue by ryantanwk** [nus-cs2103-AY1819S1/forum#100]
Hi all,

Does anyone know at which part of AB4 is user preferences in the preferences.json file read and how it is applied to the running application?

Thank you in advance

Sincerely,
Ryan

**Comment by damithc** [comment]
In the `MainApp#init()`, there is a line `userPrefs = initPrefs(userPrefsStorage);`. Is that what you are looking for?

**Comment by ryantanwk** [comment]
I found that method but I can find the actual line reads user preferences from the json file, sir

**Comment by damithc** [comment]
> I found that method but I can find the actual line reads user preferences from the json file, sir

If you talk to me after the lecture, I can show you how to locate it.

**Comment by ryantanwk** [comment]
Will do so sir, thank you

**Comment by damithc** [comment]
Closing because the issue seems to be resolved. Reopen if not.
