### ISSUE TITLE
W10.4b Typo

### ISSUE THREAD

**Issue by kohchihao** [nus-cs2103-AY1819S1/forum#103]
![screenshot 2018-10-20 at 9 10 26 am](https://user-images.githubusercontent.com/8737187/47249599-0f0c5380-d448-11e8-8939-86bc6d907b69.png)

If i am not wrong, the sequence should be 
false 
true 
false.

**Comment by damithc** [comment]
It's actually correct (it says _below_ the range the produces `true`) but some readers might misinterpret it as you did. I'll add a clarification. Thanks for reporting this @kohchihao
