### ISSUE TITLE
Is there any way to make Travis show tests logs verbosely?

### ISSUE THREAD

**Issue by davidchoo12** [nus-cs2103-AY1819S1/forum#104]
I am debugging an issue where all tests pass on our local repo but when pushed to github, fails travis build. I set up appveyor and it passes the build.

So it is an issue with travis, but travis logs tests exceptions without the actual exception messages. Is there a way of enabling verbose logs showing the exception messages and all logger messages?

**Comment by damithc** [comment]
Can you give a link to the PR?
Also, if it is passing on AppVeyor (and in your Windows Computer) but not on Travis, it might be some code that behaves differently on Unix e.g., some code involving file path separator

**Comment by davidchoo12** [comment]
Thanks for the advice!

I found out the error. It was due to file name case sensitivity in Unix.
File names are case insensitive in Windows but is case sensitive in Unix. So I fixed the file name and code to match case sensitively.

Here is the merged PR https://github.com/CS2103-AY1819S1-T13-3/main/pull/56
The latest commit in the PR fixes the issue.

**Comment by damithc** [comment]
Yup, the file name sensitivity is another Unix gotcha. :-p

**Comment by davidchoo12** [comment]
I should add that you can enable travis full exception stack trace with this extra line in build.gradle
https://github.com/CS2103-AY1819S1-T13-3/main/commit/f1e1a4547aa08543819fcbf8161fcf206267fd93
Courtesy of https://stackoverflow.com/a/47458666/4858751

Hopefully it can help others when debugging travis.
