### ISSUE TITLE
Is our team's _reposense/config.json set up correctly...?

### ISSUE THREAD

**Issue by ghost** [nus-cs2103-AY1819S1/forum#107]
...or should there be a comma after each author? This is because, according to our tutor, [there should](https://github.com/nus-cs2103-AY1819S1/addressbook-level4/pull/43#discussion_r226819244).

![image](https://user-images.githubusercontent.com/35895966/47264156-267c3700-d543-11e8-843f-a85c57f796c5.png)

I copied directly from the [setting up of RepoSense](https://nus-cs2103-ay1819s1.github.io/cs2103-website/admin/reposenseConfigTemplates.html#f11-1)

![image](https://user-images.githubusercontent.com/35895966/47264166-604d3d80-d543-11e8-82c1-1dab2a9cdd6b.png)

Much thanks in advance! :)

**Comment by ghost** [comment]
Our team's `/_reposense/config.json_` is [here](https://github.com/CS2103-AY1819S1-F11-1/main/tree/master/_reposense/config.json) by the way

**Comment by damithc** [comment]
There should be a comma after each author. The comma was omitted (by mistake) from the json file template we gave in the module website earlier (it has been added since then)

**Comment by ghost** [comment]
Okay, noted with thanks :)

**Comment by ghost** [comment]
Thanks, I think it has been set up properly now :)
