### ISSUE TITLE
RepoSense question in the case where code you contributed earlier was deleted

### ISSUE THREAD

**Issue by ghost** [nus-cs2103-AY1819S1/forum#109]
Will RepoSense "minus" a.k.a not detect the LoC (which you contributed earlier) which was deleted later?

I am not too concerned with how many LoC I wrote by the end of the semester because as per module requirements, we are expected to write about ~500-600 LoC if I remember correctly?

The reason why some code (in some cases, entire classes) was deleted from our project was due to our team doing the "morphing" direction for our ABL4.

Just for fun, here is a picture of Morphling from the MOBA game DoTA 2 :)
![image](https://user-images.githubusercontent.com/35895966/47266302-f34b9f00-d566-11e8-99c8-4cf533184402.png)

**Comment by damithc** [comment]
The code contribution shown by RepoSense contains code that exists at the latest version. Any deleted code will not be included.
