### ISSUE TITLE
How does a tutor know a particular student achieved a L/O?

### ISSUE THREAD

**Issue by ghost** [nus-cs2103-AY1819S1/forum#11]
I am asking because 1 tutor is assigned to 2 groups of 5 students in each group, so quite impossible to "check" if a student achieved a L/O. (What I mean is the duration of the tutorial is limited to 1 hour only too)

For example, last Friday, I did not get a chance to _demo_ that I did `stash`ing on SourceTree.

Perhaps, in the future (as in like from week 4 onwards _effectively_), it will be through the commits and PRs we submit? As back then it was still quite early (week 3 and before).

P.S. Anyways, even if during the tutorial, not able to "show" the evidence, I guess it is okay still :) Because the main thing is I still **learn** 👍 💯

**Comment by damithc** [comment]
> P.S. Anyways, even if during the tutorial, not able to "show" the evidence, I guess it is okay still :) Because the main thing is I still learn 👍 💯

That's the idea. It is up to the student to achieve the LOs and get help from peers/tutors if they need. The tutorial discussion is supposed to help students to self-confirm that they have achieved the LOs (e.g., from the demos, questions being discussed). There is no need for the tutor to keep track of whether a particular student achieved a specific LO. But yes, PRs done by students can give us some sense of how students are progressing.
