### ISSUE TITLE
Obtaining the correct file path for getresource()

### ISSUE THREAD

**Issue by lixinze777** [nus-cs2103-AY1819S1/forum#115]
Hi! I was facing the problem of getting a correct relative file path of my fxml file. (line 234)
![image](https://user-images.githubusercontent.com/42337990/47423236-25534000-d7b7-11e8-98d1-d1ffc2cbf107.png)
When I run the code, it gives a location is not set error. And I used the debug mode and found out that the location is indeed a null instead of the correct url.
![image](https://user-images.githubusercontent.com/42337990/47423348-5af82900-d7b7-11e8-9e7a-de4b5a77ec38.png)
But I tried a lot of possible filepaths but the location is always null. For tryout purpose, I even moved the fxml file under the same folder with the MainApp but it also did not work.
![image](https://user-images.githubusercontent.com/42337990/47423450-9bf03d80-d7b7-11e8-9090-efdc2ffb3938.png)
So my question is how could it set the file path valid? Thank you!

**Comment by damithc** [comment]
There are no similar cases in the code base?

**Comment by lixinze777** [comment]
Thank you!
If I'm not wrong, they should be in total 5 resources folders in the code base, and that is why I tried to place the fxml file inside the seedu.address folder. 
It could not explain why this still could not make it work?

**Comment by damithc** [comment]
> If I'm not wrong, they should be in total 5 resources folders in the code base, and that is why I tried to place the fxml file inside the seedu.address folder.
> It could not explain why this still could not make it work?

What I mean is, are there other fxml files  in the code base that are being used in a similar way? If there are, you can compare your code with the code of those to see if you are doing things the same way. i.e., find something that is similar and works already, and try to replicate the same.

**Comment by lixinze777** [comment]
There is a similar implementation in the fxml tutorial which I referred to.  And I did try to do the same thing, which did not actually work.
![image](https://user-images.githubusercontent.com/42337990/47428107-da402980-d7c4-11e8-8de3-681ea8ffa98d.png)

**Comment by damithc** [comment]
> There is a similar implementation in the fxml tutorial which I referred to.

You should look for similar examples in AB4 instead, as they are more likely to fit your situation. For example, look for how the `HelpWindow.fxml` is handled.

**Comment by rongjiecomputer** [comment]
@lixinze777 It should be `MainApp.class.getResource("/view/RootLayout.fxml")` (starts with `/`). Store `RootLayout.fxml` under `src/main/resources/view`.

Sidenote for others:

I was debugging my program when it failed to load a JSON file packaged as resource file only when running the program as `.jar`. For those poor souls who package non-fxml files into `.jar` file and hit the same issue, `Guava` has a `Resources` class that can make your life easier. See https://www.stubbornjava.com/posts/reading-file-resources-with-guava

**Comment by lixinze777** [comment]
Thank you!

**Comment by damithc** [comment]
@lixinze777 is the problem resolved? If it is, please close this issue.
