### ISSUE TITLE
Why was there a change from Eclipse to IntelliJ?

### ISSUE THREAD

**Issue by ghost** [nus-cs2103-AY1819S1/forum#123]
In the past, the recommended IDE was Eclipse instead of the current IntelliJ. Why was there such a change? And which semester did it start?

Just curious~

- Is it because IntelliJ is more user-friendly and easier to use for beginners to IDE?
- Is it because the UI of Eclipse looks ugly while the UI of IntelliJ looks prettier? :P

**Comment by damithc** [comment]
I got tired of students saying 'Why can't I use Intelli?', 'Intellij is the best; Eclipse sucks' etc. :-p

**Comment by ghost** [comment]
I guess it's good to be familiar with both Eclipse and IntelliJ though. We do not know what the industry outside is like, so whatever IDEs our bosses/supervisors/managers/project lead ask us to use, we have to pick it up too

**Comment by davidchoo12** [comment]
Why can't i use visual studio and C#? Jk
