### ISSUE TITLE
[curious] In the past, students could choose either C++ or Java for CS2103

### ISSUE THREAD

**Issue by ghost** [nus-cs2103-AY1819S1/forum#124]
Why did the module switch from being "bilingual" to only Java?

I understand that C++ is faster and is, in fact, the fastest language to compile and run if I am not wrong.

Also, talking about the past,
- How was it implemented? Were students given the choice to use either?
- However, were lectures and tutorials conducted using Java language? (I remember I first came across the module website _randomly_ in AY 2016/17 semester 1)
- For the group project portion, did the group have to settle with choosing either C++ or Java? (maybe it does go without saying, haha...)

Was the switch partly due to curriculum changes? (phasing out of both CS1020/e and CS2010)

Also, lastly, a _very stupidly curious_ question. What was the most number of LoC that a student wrote in a semester? (perhaps, in the past, there was no RepoSense but there was Collate tool so it was hard to individually track each student's contribution). 

Actually, not that it really matters too, haha...

**Comment by ghost** [comment]
I understand that both C++ and Java are rich with libraries. However, perhaps, Java's libraries are richer. And also, the syntax of Java (especially the data structures and classes) are more intuitive and easier to understand and/or implement than C++?

**Comment by damithc** [comment]
> Why did the module switch from being "bilingual" to only Java?

Limiting to one language allows the module to go deeper and the content can be more concrete.

> Also, lastly, a _very stupidly curious_ question. What was the most number of LoC that a student wrote in a semester?

We never kept tabs but  I remember once a student had 11k lines tagged under his/her name. That would have registered a higher number under RepoSense as RepoSense counts both tagged code and other code detected via git meta-data.
