### ISSUE TITLE
Data encryption and Constraint-Human-Editable-File?

### ISSUE THREAD

**Issue by JasonChong96** [nus-cs2103-AY1819S1/forum#130]
The constraint on the website states that : 

> The data should be stored locally and should be in a human editable text file.
> Reason: To allow advanced users to manipulate the data by editing the data file.

My group is planning to implement data encryption to encrypt data within the xml fields. e.g as shown below:
        `<name>UFx9wGWelUeFIvbJiFVwjQ==</name>`
Would it still be considered as a human editable text file if we give instructions on how to encrypt the data manually? For example using online encryption tools to encrypt the new data they want to add. Or having a encrypt string command in the application to aid them.

**Comment by damithc** [comment]
Yes, that's fine. Optionally, you can also encrypt _some_ fields but not others, to increase human editability without compromising data security.

**Comment by JasonChong96** [comment]
Alright. Thank you for the advice and quick response.
