### ISSUE TITLE
Travis seems to be building another team's closed PR 

### ISSUE THREAD

**Issue by Kratious** [nus-cs2103-AY1819S1/forum#134]
A bit of a strange issue with the Travis build on the main module repo, the build seems to be fetching from another team's PR that's been closed.

![image](https://user-images.githubusercontent.com/6714460/47791210-1f7bd280-dd54-11e8-95ae-dc6e3a257d80.png)

Here's the build [link](https://travis-ci.org/nus-cs2103-AY1819S1/addressbook-level4/builds/448713814?utm_source=github_status&utm_medium=notification) and the PR that's being fetched by Travis - https://github.com/nus-cs2103-AY1819S1/addressbook-level4/pull/165

The log is showing errors for changes that my team hasn't made.
![image](https://user-images.githubusercontent.com/6714460/47791526-e2641000-dd54-11e8-9224-899a9d6eca3b.png)

Any suggestions on how to fix?

**Comment by damithc** [comment]
Could be a Travis problem. Try opening a new PR. If that one works, you can close the failing one.

**Comment by Kratious** [comment]
OK, so we opened a new PR with a test branch and Travis passed there. Then closed the test PR. After closing the test PR, the travis build on our original PR passed (somehow).
