### ISSUE TITLE
Using external Google Calendar Java API and Free Currency Converter API for our project

### ISSUE THREAD

**Issue by aaditkamat** [nus-cs2103-AY1819S1/forum#137]
I just wanted to inform for user testing purposes during the dry run tomorrow that we are using the above mentioned 3rd party software. The links to these are as follows:
1) [Google Calendar Java API](https://developers.google.com/calendar/quickstart/java)
2) [Free Currency Converter API](https://free.currencyconverterapi.com/)

**Comment by ghost** [comment]
Good luck! :)

**Comment by damithc** [comment]
> I just wanted to inform for user testing purposes during the dry run tomorrow that we are using the above mentioned 3rd party software. The links to these are as follows:

Inform who? The testers of your product are unlikely to read this post :-)

**Comment by jackedelic** [comment]
Noted with thanks.

-- your potential tester

**Comment by rongjiecomputer** [comment]
Is this a warning that the application can potentially mess up the tester's personal Google Calendar?

**Comment by aaditkamat** [comment]
We will be a providing a test Google Account to prevent that.

**Comment by damithc** [comment]
> Yeah we will be a providing a test Google Account for that.

Do include all that info in the user guide as testers will test based on the UG only.
