### ISSUE TITLE
If there is such a thing as Software Engineering, is there Hardware Engineering too?

### ISSUE THREAD

**Issue by ghost** [nus-cs2103-AY1819S1/forum#138]
![image](https://user-images.githubusercontent.com/35895966/47863681-c6cf3700-de32-11e8-916a-7deb01298e53.png)

... and do they go hand in hand? :o

**Comment by ghost** [comment]
Maybe it's just called 

> Electrical Engineering

**Comment by ghost** [comment]
Computer Architecture? Pretty sure that is close to what you are talking about.

**Comment by ghost** [comment]
> Computer Architecture? Pretty sure that is close to what you are talking about.

Aww man... I have to take a module on that in the future :/

Anyways, my understanding is that Computer Architecture is also _quite related_ to software stuff, hence intertwined. Basically, maybe hardware and software are usually intricately linked together I guess? :)

**Comment by Nelda621** [comment]
Yes, just as there is Software Engineering, there is also Hardware Engineering. Software Engineering focuses on designing, developing, and maintaining software systems, while Hardware Engineering deals with the physical components and systems of technology, such as circuit boards, processors, and memory devices. Both fields are essential in creating integrated solutions for modern technology, and they often work in tandem to deliver a seamless user experience.

For more details on software development processes, you can visit this link: [https://www.cleveroad.com/blog/enterprise-software-development-process/](https://www.cleveroad.com/blog/enterprise-software-development-process/)
