### ISSUE TITLE
Travis throws HeadLessException

### ISSUE THREAD

**Issue by leo-1997** [nus-cs2103-AY1819S1/forum#141]
I have added a command which basically copies string to the system clipboard. The test which checks the command successfully passed on my laptop but failed in Travis. Travis throws a HeadLessException which is probably due to it doesn't have a keyboard. How can i solve this?

**Comment by eugenepeh** [comment]
@leo-1997 i am unable to find this issue on your travis. Can you please post the link to the log that contains your error?

**Comment by eugenepeh** [comment]
On a side note, I found similar issues on SO which might be useful for your case.
https://stackoverflow.com/questions/51004447/spring-boot-java-awt-headlessexception
https://stackoverflow.com/questions/52812363/getsystemclipboard-failed-on-headless-exception

**Comment by leo-1997** [comment]
https://travis-ci.org/CS2103-AY1819S1-T12-4/main
here is the link to the travis. really sorry

**Comment by leo-1997** [comment]
Thank you i have solved the problem
