### ISSUE TITLE
PE Dry Run issues not submitted

### ISSUE THREAD

**Issue by OrangeJuice7** [nus-cs2103-AY1819S1/forum#144]
I've participated in the PE Dry Run but I didn't know that we had to post the issues immediately. I was taking notes on NotePad instead, and planned to add them as issues later (before I go home for the day). But the private issue tracker closed soon after, and now I can't do that. Help please?

**Comment by damithc** [comment]
@FongYuan which team?

**Comment by NancyQuris** [comment]
Dear Prof, I also encountered the same problem as Fong Yuan. I hope to get a chance to compile and submit my report as well since I did encounter some problems when testing the product and I hope my report could more or less help them. I was testing W10-4's product.

**Comment by damithc** [comment]
> Dear Prof, I also encountered the same problem as Fong Yuan. I hope to get a chance to compile and submit my report as well since I did encounter some problems when testing the product and I hope my report could more or less help them. I was testing W10-4's product.

@NancyQuris You can post directly in their issue tracker. In the first issue, mention why you are posting directly.

@FongYuan you can do the same.

**Comment by NancyQuris** [comment]
> > Dear Prof, I also encountered the same problem as Fong Yuan. I hope to get a chance to compile and submit my report as well since I did encounter some problems when testing the product and I hope my report could more or less help them. I was testing W10-4's product.
> 
> @NancyQuris You can post directly in their issue tracker. In the first issue, mention why you are posting directly.
> 
> @FongYuan you can do the same.

Noted with thanks!

**Comment by OrangeJuice7** [comment]
Alright, thank you!

**Comment by damithc** [comment]
@FongYuan @NancyQuris I forgot to mention. Please email me links to your bug reports, for our records, in case we need them for grading purposes later.
