### ISSUE TITLE
Is there a way to browse the commit/edit history of ONE particular file in your project?

### ISSUE THREAD

**Issue by ghost** [nus-cs2103-AY1819S1/forum#147]
As per title

**Comment by ghost** [comment]
Like for instance, when we first drafted our `[GITHUB_USERNAME].adoc` weeks ago I think?

**Comment by azhikai** [comment]
Click on the file of interest and click `History`

![image](https://user-images.githubusercontent.com/7473075/47925900-2e9c8500-defa-11e8-90ab-d290b76d54f3.png)

**Comment by ghost** [comment]
Or, perhaps, by "filtering" commits by author's username? (sorry for the possible spam in comments... in the own thread which I started though, haha~)

**Comment by ghost** [comment]
> Click on the file of interest and click `History`
> 
> ![image](https://user-images.githubusercontent.com/7473075/47925900-2e9c8500-defa-11e8-90ab-d290b76d54f3.png)

Ahh okayyy I see, thanks!

Because I wanted to answer the issue on the PPP clarification. And show my funny version of my own PPP (at that time). Hahaha~ Looks like I did not push the code and left it locally. (maybe it was supposed to be for some tutorial exercise :o)

(Basically it was like modifying from the existing template and writing ridiculous things HAHAHAHA)

Wait, btw, is the for example `heartofal1on.adoc` and the PPP the same thing?

**Comment by azhikai** [comment]
> > Click on the file of interest and click `History`
> > ![image](https://user-images.githubusercontent.com/7473075/47925900-2e9c8500-defa-11e8-90ab-d290b76d54f3.png)
> 
> Ahh okayyy I see, thanks!
> 
> Because I wanted to answer the issue on the PPP clarification. And show my funny version of my own PPP (at that time). Hahaha~ Looks like I did not push the code and left it locally. (maybe it was supposed to be for some tutorial exercise :o)
> 
> (Basically it was like modifying from the existing template and writing ridiculous things HAHAHAHA)
> 
> Wait, btw, is the for example `heartofal1on.adoc` and the PPP the same thing?

Whatever you wrote in your `name.adoc` should be used for the PPP submission.

**Comment by aaditkamat** [comment]
> Whatever you wrote in your `name.adoc` should be used for the PPP submission.

Is it mandatory to include the respective asciidocs in the docs/team folder of your project? I thought that the final submission is in PDF format. From  #146, it seems like you make use of the html generated by the GitHub Pages for the PPP after conversion to PDF, but you can do that using [asciidoctor-pdf](https://github.com/asciidoctor/asciidoctor-pdf) utility as well.

**Comment by ghost** [comment]
> > Whatever you wrote in your `name.adoc` should be used for the PPP submission.
> 
> Is it mandatory to include the respective asciidocs in the docs/team folder of your project? I thought that the final submission is in PDF format. From #146, it seems like you make use of the html generated by the GitHub Pages for the PPP after conversion to PDF, but you can do that using [asciidoctor-pdf](https://github.com/asciidoctor/asciidoctor-pdf) utility as well.

Yes final submission of the PPP should be rendered in PDF format. In your case, I think you need to render the `aaditkamat.adoc` file to PDF format :)
