### ISSUE TITLE
[suggestion for website] Give each .card-header unique ids so that users can share link to the card

### ISSUE THREAD

**Issue by davidchoo12** [nus-cs2103-AY1819S1/forum#15]
Something like in https://developers.timekit.io/v2/reference#section-app-specific-requests
![image](https://user-images.githubusercontent.com/7817101/44995857-8e001680-afd7-11e8-8e4e-9f2ad1c683f5.png)
The anchor icon appears on hover in the website but you can implement it as a button or a link.

Occasionally, I feel the need to share specific section of the page to my team.

**Comment by davidchoo12** [comment]
Oops I thought this was the website repo. What should I do if I posted an issue to a wrong repo in real life scenario?

**Comment by damithc** [comment]
That's a good suggestion @hidingmode 👍 I'll cross post in the MarkBind issue tracker for the tool developers to consider it as a feature for future versions.
You posted in the correct place. It's easier for everyone if all module related issues are posted here.
If you post in the wrong issue tracker, you can simply say it was the wrong place and close the issue yourself.

**Comment by damithc** [comment]
Feature implemented. The first version is slightly buggy; being fixed at the moment.
