### ISSUE TITLE
Request to use external library Google Maps JS API

### ISSUE THREAD

**Issue by Lexzt** [nus-cs2103-AY1819S1/forum#155]
Hi prof

https://developers.google.com/maps/documentation/

We would like to use Google Maps API to display markers and update it accordingly to every command we type. In our case, we would like to showcase where our car park is located.

Regards,
Keith

**Comment by damithc** [comment]
Approved. Note that the API might block calls from your CI tests if it suspects the calls are coming from a bot.

**Comment by ghost** [comment]
> Approved. Note that the API might block calls from your CI tests if it suspects the calls are coming from a bot.

Ohh, interesting... My team uses Google Calendar API and we had some problems passing even Travis and/or AppVeyor CI tests previously.

It took very long and I think there were instances where the tests failed.

Anyway, it wasn't my part but if I have the time, I would like to find out why too :)

**Comment by Lexzt** [comment]
Hey, so I am using the js side of it, meaning the html is loaded async and defer. Meaning it does not matter as the bot currently tests the url of the website and since I am only parsing small sets of information to the display side, it does not hold up anything!
