### ISSUE TITLE
Request to use external library SVY21

### ISSUE THREAD

**Issue by Lexzt** [nus-cs2103-AY1819S1/forum#156]
Hi Prof,

https://github.com/cgcai/SVY21

We would like to use this library to convert our SVY21 coordinates to WGS84 coordinates to fit into our Google Maps API we previously requested. As all data coming from data.gov.sg is in SVY21 and the calculations for converting it is very complex, we found a simple library to do the conversion for us.

Regards,
Keith

**Comment by damithc** [comment]
Approved.
