### ISSUE TITLE
Re-clarification needed regarding labels for issues

### ISSUE THREAD

**Issue by ghost** [nus-cs2103-AY1819S1/forum#157]
These are some of the labels my team uses:
![image](https://user-images.githubusercontent.com/35895966/48001505-b88b5e80-e143-11e8-82ab-3f34dfab16aa.png)

For issues assigned to our team by the cs2103-feedback-bot after the PE on week 13, we should only use these 3 labels as below so the scripts can work?
![image](https://user-images.githubusercontent.com/35895966/48001447-9560af00-e143-11e8-80fc-e63856293ff8.png)

I thought of assigning the weekly labels to issues, but my "OCD" tendencies took hold of me so I assigned them accordingly to EVERY single issue and PR, regardless open or closed XD. For PE, I should not assign these labels (and any other labels) except the "severity" labels so the script can work?

**Comment by damithc** [comment]
You can do whatever with PE Dry Run bug reports. It's entirely up to you :-)
We have strict processing requirements for PE ~~Dry Run~~ bug reports, but that's something that will happen in week 13.

**Comment by ghost** [comment]
Okay, thanks, Prof!
