### ISSUE TITLE
Do we need to change the email address for the "Contact Us" section?

### ISSUE THREAD

**Issue by ghost** [nus-cs2103-AY1819S1/forum#158]
This is my team's `docs/ContactUs.adoc` currently:
![image](https://user-images.githubusercontent.com/35895966/48037931-7137b900-e1a9-11e8-95bd-d14492795481.png)

Hence, I would like to ask if it is required to change the email address from Prof's email address to _possibly_ our team lead's email? Or perhaps even our team's email (if we have one)?

**Comment by damithc** [comment]
Yes, you can. Not required though. You can also use a generic email such as `cs2103[at]comp.nus.edu.sg`
