### ISSUE TITLE
Use Case MSS always starting with User

### ISSUE THREAD

**Issue by YuPeiHenry** [nus-cs2103-AY1819S1/forum#16]
In the examples given on the website, the MSS for Use Cases seem to always start with the User performing an action. In a scenario where the system provides information to the user while idling, does the Use Case still start with the User performing an action? (i.e. System shows a dashboard with information during normal/idle operation, and the User performs an action using the information shown).

**Comment by damithc** [comment]
There is no rule that the first use case step should always be from the user, but that's the more common scenario. For your example, you can still starts with the user if you want. e.g.,
>1. User monitors the dashboard
>1. Dashboard indicates a ...

**Comment by damithc** [comment]
Closing as the question seems to be answered. Feel free to reopen if not.
