### ISSUE TITLE
Is the textbook okay to print? 

### ISSUE THREAD

**Issue by kohchihao** [nus-cs2103-AY1819S1/forum#166]
Good afternoon Prof @damithc ,

I would like to check if the textbook is okay to print right now? Because you said last time, there might be things to finalise.

**Comment by damithc** [comment]
Yes, you can go ahead @kohchihao I recently cleaned up the printable version.

**Comment by ghost** [comment]
What if I printed it very early, like first few weeks of the sem? :/

Yes, I noticed some images were broken images

**Comment by damithc** [comment]
> What if I printed it very early, like first few weeks of the sem? :/

It's updated over the semester, although in minor ways.

**Comment by ghost** [comment]
Looks like I will just reprint again. [don't worry, I will find a way to recycle my previous binded textbook ;)]
