### ISSUE TITLE
W4.11e tests classes cannot find symbols

### ISSUE THREAD

**Issue by davidchoo12** [nus-cs2103-AY1819S1/forum#17]
I am just sharing it here in case anyone face the same problem I had.

I encountered a problem while following the Developer Guide for task W4.11e where the classes in the test folder is unable to resolve symbols/classes from the src folder. Example below:
![image](https://user-images.githubusercontent.com/7817101/45082453-ef38fe80-b12b-11e8-9fb1-a773030dee06.png)

I followed the guide until step 13 ("Run the tests again to ensure they all pass now") but still failed because of the unresolved symbols.
I suspected it has got to do with some classpath issues. Watching the junit intro video made me check the project structure in intellij and found out that the src folder was not marked as source.
![image](https://user-images.githubusercontent.com/7817101/45082799-bcdbd100-b12c-11e8-8506-b8b4f2e67484.png)

Marking it as source resolves the issue.

**Comment by damithc** [comment]
Closing as this is probably no longer relevant. Thanks again for sharing this.
