### ISSUE TITLE
Regarding overview section in PPP

### ISSUE THREAD

**Issue by ghost** [nus-cs2103-AY1819S1/forum#171]
Is it better for the team to standardize the Overview section in PPP?

For example, in the [original](https://github.com/nus-cs2103-AY1819S1/addressbook-level4/tree/master/docs/team/johndoe.adoc), it looks something like this:

![image](https://user-images.githubusercontent.com/35895966/48314533-e110ce00-e605-11e8-96e0-722d9a084add.png)

Is it necessary to standardize this section across the team?

**Comment by ghost** [comment]
I would also like to ask about the code size. Is there a way to determine the total kLoC in a repo?

Is it okay to give a guesstimate of 20 kLoC?

**Comment by damithc** [comment]
> Is it better for the team to standardize the Overview section in PPP?

Up to you. All team members can use the same overview, or each one can write your own.



> I would also like to ask about the code size. Is there a way to determine the total kLoC in a repo?

There is an Intellij plugin called _statistics_ (or something like that) that can give you the LoC stats.

**Comment by ghost** [comment]
I think I found the answer

https://stackoverflow.com/questions/3435581/how-to-count-lines-of-java-code-using-intellij-idea

**Comment by ghost** [comment]
Hi, just to check, if counting total LoC in a project, we only count Java code?

![image](https://user-images.githubusercontent.com/35895966/48314862-a493a100-e60a-11e8-9944-3be551ca9792.png)

So for above, it is around 21 kLoC, and not 175 kLoC? (with regards to the codebase size for the Overview section of the PPP)

**Comment by damithc** [comment]
> Hi, just to check, if counting total LoC in a project, we only count Java code?

Up to you. Anything you wrote can be considered code,.

**Comment by ghost** [comment]
Wow, imagine if the sandboxmanypersons file thingy was counted as part of statistic? That's like 75 kLoC free iirc xD

P.S. the team that has that file committed to their repo might be penalised though? :o
