### ISSUE TITLE
Converting asciidoc to pdf

### ISSUE THREAD

**Issue by monmanuela** [nus-cs2103-AY1819S1/forum#172]
Hi, I tried to convert asciidoc to pdf by first running `gradlew asciidoctor` and then using chrome to save as pdf.
The links in the asciidoc file look fine in html:
![image](https://user-images.githubusercontent.com/35655790/48314811-f2f47000-e609-11e8-9703-19641cdb4220.png)
But after saving as pdf, the links look like this in pdf:
![image](https://user-images.githubusercontent.com/35655790/48314820-1f0ff100-e60a-11e8-8bee-5bfee470112e.png)

This seems to be the expected behavior. Is there another way I can convert asciidoc to pdf and not make the links look ugly? Thanks!

**Comment by yamgent** [comment]
You can delete line 381 of `docs/stylesheets/asciidoctor.css` in order to get rid of the trailing URLs after the main hyperlinks. The hyperlinks themselves will remain clickable after the URLs are removed.

Line 381 is this line:

![line381](https://user-images.githubusercontent.com/3168908/48315051-76af5c00-e60c-11e8-8cf8-5e29f9d25241.png)

**Comment by ganchinyao** [comment]
Alternatively you can add this inside your stylesheet


```
@media print {
  a[href]:after {
    content: none !important;
  }
}
```

**Comment by monmanuela** [comment]
Thanks! Removing line 381 in `asciidoctor.css` works

**Comment by HEARTOFAL1ON** [comment]
> @media print { a[href]:after { content: none !important; } }

Hey there, do we create a new file under `docs/stylesheets` and if so, what should we name it?

**Comment by ghost** [comment]
> Alternatively you can add this inside your stylesheet
> 
> ```
> @media print {
>   a[href]:after {
>     content: none !important;
>   }
> }
> ```

@NightYeti Hey there, do we create a new file under `docs/stylesheets` and if so, what should we name it?

**Comment by ganchinyao** [comment]
> > Alternatively you can add this inside your stylesheet
> > ```
> > @media print {
> >   a[href]:after {
> >     content: none !important;
> >   }
> > }
> > ```
> 
> @NightYeti Hey there, do we create a new file under `docs/stylesheets` and if so, what should we name it?

Hi 
You can just add it in the first line of `asciidoctor.css` found in `docs/stylesheets`. Save it, and you should be able to generate a html file of your .adoc, and save it to .pdf like what the DG has written. The extra link should not be printed on your pdf file.

**Comment by ghost** [comment]
Nvm I solved it by simpling adding a new line (on line 408) and typing
`@media print {a[href]:after{content: none !important;}}`

and it works! :)
