### ISSUE TITLE
Where to upload the .pdf files on IVLE?

### ISSUE THREAD

**Issue by ganchinyao** [nus-cs2103-AY1819S1/forum#174]
Hi

As stated on the CS2103 website, 

![screen shot 2018-11-12 at 12 03 20 am](https://user-images.githubusercontent.com/30016307/48315222-68623f80-e60e-11e8-9eed-6748d16906dd.png)

However, I could not find any folder to upload them on IVLE. Specifically, I navigated to CS2103t -> Files -> Student Submission.

I only saw v1.0 inside Student Submission folder.

Where can we find the folder to upload v1.4 to?

In addition, can I know if only 1 person needs to upload the file, or everyone in the team has to upload a copy to the folder?

Thanks!

**Comment by damithc** [comment]
Created the IVEL folder `v1.4` just now. Sorry about that.
