### ISSUE TITLE
Indentation error in DG 

### ISSUE THREAD

**Issue by spencertan96** [nus-cs2103-AY1819S1/forum#175]
My indenting doesn't seem to work for this one case, and I'm not sure why.
Extract: 
![image](https://user-images.githubusercontent.com/42445828/48315840-4ff62300-e616-11e8-9c88-efed27c424de.png)
Code: 
![image](https://user-images.githubusercontent.com/42445828/48315845-669c7a00-e616-11e8-9379-af5d247c1441.png)
I put the `//` there when I found out that they reduced the indentation of `Alternative 2` by one, but it is still one more than it should be. Removing it would make the indentation look like: 
![image](https://user-images.githubusercontent.com/42445828/48315858-93509180-e616-11e8-85f4-1cab98f4ebce.png)
I have similar indentation elsewhere that works though, 
Extract: 
![image](https://user-images.githubusercontent.com/42445828/48315868-b0856000-e616-11e8-9b89-1bd718746b38.png)
Code: 
![image](https://user-images.githubusercontent.com/42445828/48315874-ba0ec800-e616-11e8-89cf-e6e53f4104a9.png)
Not sure why there is this discrepancy!

**Comment by yamgent** [comment]
It is likely that Asciidoc is confused about the relationship between the list(s) for the buggy case, whereas in the other places Asciidoc got lucky and guessed the indentation correctly.

You can use `+` between the empty lines to signal to Asciidoc that everything belongs to the same list, so that the indentation is done correctly:

```
* **Alternative 1 (current choice):** Use `note` command in implementation.
+
.Structure of Note commands (only classes closely related to EditNoteCommand shown)
image::EditNoteFeatureClassDiagram.png[width="800"]
+
** Pros: +
*** Easier to implement.
*** Adapts with any changes to the `NoteCommand` without needing to update.
** Cons: +
*** Some overhead accrued due to `NoteCommand` object creation.
*** Dependency between `EditNoteCommand` and `NoteCommand`.
+
* **Alternative 2:** Implement a separate edit note command.
** Pros: +
*** Command will be able to work on its own.
** Cons: +
*** Some repeated code with `NoteCommand`.
```

**Comment by spencertan96** [comment]
Alright thank you!! It seems that adding `+` from `Alternative 1` to `Pros` fixed it, maybe the diagrams caused the confusion? Then again I have a diagram in another section too that worked
