### ISSUE TITLE
Not sure why i'm getting this: "ERROR: only book doctypes can contain level 0 sections"

### ISSUE THREAD

**Issue by thaddeuslzy** [nus-cs2103-AY1819S1/forum#176]
My Travis CI build suddenly fails because of this error, and I do not know why this is suddenly the case, because I do not recall making any changes to the asciidoctor. The "=" prefix for titles like "= Student Schedule Planner - Developer Guide" should be fine correct? Can anyone help me with this issue? I cannot merge any changes because the build keeps failing

asciidoctor: ERROR: /home/travis/build/thaddeuslzy/main/docs/DeveloperGuide.adoc: line 1: only book doctypes can contain level 0 sections

Line 1: = Student Schedule Planner - Developer Guide

asciidoctor: ERROR: /home/travis/build/thaddeuslzy/main/docs/UserGuide.adoc: line 12: only book doctypes can contain level 0 sections

Line 2: = Student Schedule Planner - User Guide

<img width="376" alt="screen shot 2018-11-12 at 1 01 44 pm" src="https://user-images.githubusercontent.com/40333905/48327721-40f58c00-e67b-11e8-8798-054fc1b446cc.png">

<img width="1004" alt="screen shot 2018-11-12 at 1 01 11 pm" src="https://user-images.githubusercontent.com/40333905/48327713-3804ba80-e67b-11e8-821c-825b4896e3ff.png">

**Comment by yamgent** [comment]
`docs/team/thaddeuslzy.adoc` contains includes to the `UserGuide.adoc` and `DeveloperGuide.adoc` without tags specified. When tags are not specified, the **entire** user/developer guide is included, which causes the multiple level 0 error (headings that start with one `=` are level 0 headings).

Removing these includes with empty tags should solve the issue:

```
include::../UserGuide.adoc[tag=]

include::../UserGuide.adoc[tag=]

...

include::../DeveloperGuide.adoc[tag=]

include::../DeveloperGuide.adoc[tag=]
```

**Comment by thaddeuslzy** [comment]
@yamgent Thank you! It works now :)
