### ISSUE TITLE
Reposense still doesn't detect my code despite following steps from previous issues to solve it

### ISSUE THREAD

**Issue by neilish3re** [nus-cs2103-AY1819S1/forum#177]
Hi Prof @damithc , despite following all the suggestions above,  Project Code Dashboard (BETA) reposense still doesnt detect my code.
When I run reposense locally, all my code is detected correctly. Even my group member could detect my code when she ran reposense on her computer as well
I even updated the config.json file to include my other possible authornames.

What else can I do?

**Comment by park-sang-jun** [comment]
Same here. The Project Code Dashboard does not reflect any of the commits I have made, but the report generated by running RepoSense locally correctly shows my commits.

**Comment by damithc** [comment]
_Project Code Dashboard (BETA)_ is generated only at certain times. Please check the latest version (I generated it a few minutes ago) and let us know if your code is still not detected. 
Also note that your updated config.json file need to be pushed to your master branch for us to be able to use it.

**Comment by neilish3re** [comment]
The issue has been resolved after you generated Project Code Dashboard (BETA) again.
Thanks Prof!
