### ISSUE TITLE
Very happy after tonight

### ISSUE THREAD

**Issue by ghost** [nus-cs2103-AY1819S1/forum#183]
Not really an issue, but just want to say I am so happy that we can FINALLY forget about

CS2103 project after tonight! :D

More or less~

(except for Friday PE :P)

**Comment by rongjiecomputer** [comment]
Same here, but don't forget about the product demo too!

**Comment by ghost** [comment]
Thank you Prof @damithc and other members of the wonderful teaching team! :D

**Comment by ghost** [comment]
> Same here, but don't forget about the product demo too!

Oh yeah... during tutorial! :P

**Comment by ghost** [comment]
Shoutout to the developers of the ABL1-4 projects too! (Some of whom may not _necessarily_ be part of the teaching team this sem, but whom also offer help. However, as we also know, some have also been working tirelessly in the background)
