### ISSUE TITLE
Issue with test code

### ISSUE THREAD

**Issue by ngkangtze** [nus-cs2103-AY1819S1/forum#186]
This is with reference to the recent RepoSense email.

> Guys, please check RepoSense dashboard (warning: it takes some time to load) to see if it is showing your code correctly. It's fine if the Ramp Chart and the contribution bar doesn't match your work (we don't use them for grading) but make sure the code reflected in the Code View (click on your name to see the Code View) as we use Code View to grade your code quantity/quality.
If needed, you can update the _reposense/config.json file and/or @@author tags to tweak RepoSense output (other changes are not allowed). While this was something you should have done before the deadline, we'll allow an amnesty period until this Saturday midnight (17th Nov) to do RepoSense tweaks without a penalty, given that RepoSense is a new tool and there were some teething problems earlier. If you need help with configuring RepoSense, please post in our forum. 

At the moment, a large portion of my code does not show up on the side panel in RepoSense, and fixing this will require me to commit some changes to the main repo.

However, there is a problem with resubmission with regards to the passing of tests in our code. In particular, this method:

<img width="1792" alt="screenshot 2018-11-15 at 3 48 02 pm" src="https://user-images.githubusercontent.com/39233627/48538138-9a192600-e8ee-11e8-95f8-d1d86883f311.png">
<img width="1792" alt="screenshot 2018-11-15 at 3 46 58 pm" src="https://user-images.githubusercontent.com/39233627/48538145-9d141680-e8ee-11e8-9fc9-cf39aee1d420.png">

As can be seen in the screenshots above, our tests for the code utilise the current date in order to check if the entered date is valid. (i.e. we are not allowed to schedule an appointment to a date that is in the past with respect to the current date.) This date is updated in realtime.

This means that while our tests passed at the point of submission, committing a change for RepoSense now will result in the tests re-running and failing because the current date is after the date of submission. (The date scheduled for the appointment in the test was 12.11.2018, which would result in a valid schedule at the time of submission.)

My question is can we be allowed to make this change in the test cases when recommitting changes to fix RepoSense without the deduction of marks?

**Comment by damithc** [comment]
> My question is can we be allowed to make this change in the test cases when recommitting changes to fix RepoSense without the deduction of marks?

OK, go ahead. For future reference, this is a flaw in your tests -- they should not be time sensitive in this way.

**Comment by ngkangtze** [comment]
Understood. Thanks Prof.
