### ISSUE TITLE
Unable to launch JAR [T13-3]

### ISSUE THREAD

**Issue by anubh-v** [nus-cs2103-AY1819S1/forum#187]
Hi everyone,
This message is intended for team T13-3. The product name is JxMusic.

I was unable to launch the JAR file.
Here is the [stack trace](https://github.com/nus-cs2103-AY1819S1/forum/files/2585184/trace.txt)
I am using Linux Mint v18.3

**Comment by damithc** [comment]
Which OS?

**Comment by anubh-v** [comment]
My apologies - I have updated the post

**Comment by NancyQuris** [comment]
Do you get the library folder generated?
https://github.com/CS2103-AY1819S1-T13-3/main/blob/master/docs/DeveloperGuide.adoc#instructions-for-manual-testing
This link might be helpful for you

**Comment by anubh-v** [comment]
Yes, but it is empty. `config.json`, `preferences.json` and a `jxmusic` log file are also generated.

**Comment by NancyQuris** [comment]
I am not sure about this case since none of my team members uses Linux. 
No sure if it is helpful, but can you try `unzip jxmusic.jar "library/*"` it again and see how...

**Comment by davidchoo12** [comment]
The jar runs by enterring in the command line:
`java -jar <file name>.jar`
If that also fails, enter in command line:
`unzip <file name>.jar "library/*"`
If that also fails, please download the [library zip](https://github.com/CS2103-AY1819S1-T13-3/main/releases/download/v1.3/library.zip)

**The jar does not work by double clicking on first run**, which is a known issue.
Once the library folder exists with the sample tracks, subsequent launches can be done by double clicking.

**Comment by anubh-v** [comment]
Ok. I can start the JAR after unzipping the library files.

**Comment by NancyQuris** [comment]
Cool!
