### ISSUE TITLE
Is it possible to "delete" issues in our group's repo named "main"?

### ISSUE THREAD

**Issue by ghost** [nus-cs2103-AY1819S1/forum#19]
As per above.

Seems like can only edit the title right? :(

Let's say you want to remove an issue. Maybe perhaps just comment something that says the issue is "not really an issue" or I am not very sure how to explain. Maybe like "This is not an issue. It will be closed.". Something like that?

**Comment by azhikai** [comment]
Not possible. Just close it if it's a mistake, but indicate a comment so others know why you closed it.
