### ISSUE TITLE
Unable to decide response.Accpect or response.Rejected

### ISSUE THREAD

**Issue by YipZong** [nus-cs2103-AY1819S1/forum#194]
Hi Prof. Damith,
Our team is having an issue to decide the following tag: `response.Accpect` or `response.Rejected.`

The situation is as below:
Initially, we wanted to split the command `list `to `listTag `and `listEvent`, so in the command summary (and **only in the command summary**, the main text does not have the description for `listTag `and `listEvent`, we put the following in the command summary,

> listTag: ...
> listEvent:...

However, we decided to implement other commands instead but forgot to update the documentation for command summary. Our app hence actually only have `list `command, but not  `listTag ` or`listEvent`

If `listTag `is reported as an invalid command by the tester, this command is expected **not able to work** to us. But to a user, the user might expect such commands by referring to the command summary.
Which is the best option to tag?
a) accept + documentation error
b) reject + documentation error

Thank you!

**Comment by damithc** [comment]
The phrase ` forgot to update the documentation` suggests it's a documentation bug :-)

**Comment by YipZong** [comment]
ok! thank you!

**Comment by YipZong** [comment]
Sorry just to confirm, can we change the severity to `low `for such documentation bug? Thank you.

**Comment by damithc** [comment]
> Sorry just to confirm, can we change the severity to `low `for such documentation bug? Thank you.

Yes, if you think the bug fits the definition of a severity.Low bug :-)

**Comment by YipZong** [comment]
ok! I will state the reasons! Thank you!
