### ISSUE TITLE
Okay to reject a minor documentation bug like this?

### ISSUE THREAD

**Issue by ghost** [nus-cs2103-AY1819S1/forum#196]
https://github.com/nus-cs2103-AY1819S1/pe-results/issues/142

IMO, I think as long as a student explain quite clearly and succinctly the reasons for rejecting a minor bug, it is okay to attach a `reponse.Rejected` label?

Also, we may or may not be thinking of having more than one person assigned to this bug.

Thank you!

**Comment by ghost** [comment]
Oh yeah, on another note, is it perfectly alright to have closed this issue too?

Anyhow, perhaps the scripts might reopen it 😁

**Comment by damithc** [comment]
> IMO, I think as long as a student explain quite clearly and succintly the reasons for rejecting a minor bug, it is okay to attach a `reponse.Rejected` label?

Sure. If it is minor typo, we recommend accepting as a `severity.Low` `type.Documentation` bug as it _is_ a bug that needs fixing. But you can group all typo/grammar bugs as duplicates of one bug.

**Comment by ghost** [comment]
Okay thanks Prof! :)

**Comment by ghost** [comment]
Hi Prof @damithc, same issue, and I need reclarification again if possible 😃 

![image](https://user-images.githubusercontent.com/35895966/48659598-6d037980-ea8e-11e8-91af-0ce0b61d8f58.png)

So for the image above, I am only willing to accept responsibility for the minor typo of the highlighted part, but not other things in the "bug", and that is why I assigned myself as the assignee.

Can I do that? In addition, we also decided to tag this issue with the `response.Rejected` tag.

Maybe it is actually better to un-assign me from this? (as above, I also explained the reasoning behind the rejection for that typo, but there is also reasoning offered for the other parts of the bug, just not by myself)

Thank you!

Warmest Regards,
Dan

**Comment by azhikai** [comment]
> Hi Prof @damithc, same issue, and I need reclarification again if possible 😃
> 
> ![image](https://user-images.githubusercontent.com/35895966/48659598-6d037980-ea8e-11e8-91af-0ce0b61d8f58.png)
> 
> So for the image above, I am only willing to accept responsibility for the minor typo of the highlighted part, but not other things in the "bug", and that is why I assigned myself as the assignee.
> 
> Can I do that? In addition, we also decided to tag this issue with the `response.Rejected` tag.
> 
> Maybe it is actually better to un-assign me from this?
> 
> Thank you!
> 
> Warmest Regards,
> Dan

> Sure. If it is minor typo, we recommend accepting as a severity.Low type.Documentation bug as it is a bug that needs fixing. But you can group all typo/grammar bugs as duplicates of one bug.

I think this pretty much explained everything.

In this case, I'd accept it as a documentation bug, with low severity.

**Comment by ghost** [comment]
Okay, thank you for input for now :)

It can definitely be marked as a duplicate of a typo/grammar bug, as it is one itself though.
