### ISSUE TITLE
[LO W4.1c] Having problems pushing a branch from local repo to fork

### ISSUE THREAD

**Issue by ghost** [nus-cs2103-AY1819S1/forum#20]
Even though I typed the correct GitHub username/email and password

![image](https://user-images.githubusercontent.com/35895966/45143224-3b984300-b1ed-11e8-8a1f-2f36c7a662fd.png)

This is a ss (screenshot) of the step before:
![image](https://user-images.githubusercontent.com/35895966/45143270-62567980-b1ed-11e8-8f3c-0f38b00c3b24.png)

Btw, this is on SourceTree :)

Btw, the settings are correct right?
![image](https://user-images.githubusercontent.com/35895966/45143300-7ac69400-b1ed-11e8-9a83-6551f5ff030d.png)
![image](https://user-images.githubusercontent.com/35895966/45143323-8b770a00-b1ed-11e8-801c-583f91cbf3eb.png)

**Comment by ghost** [comment]
I have tried closing the SourceTree program and even to the point of ending the SourceTree process in the Task Manager (if there is one even after I close the program, but usually there isn't such a process still lying around). However, it still doesn't work.

As un-intuitive as it may sound, the only thing I have not tried is restarting my Windows PC (laptop). Maybe it may work, lol~

EDIT: Just realized it could be because I am have enabled and I am using 2FA for my GitHub account. Let me try removing and see if SourceTree allows me to push a branch to my fork.

EDIT2: Wow, really, after disabling 2FA on my GitHub, I can now push the branch from my local repo to my fork using SourceTree. Looks like SourceTree and GitHub's 2FA don't go well together :(

**Comment by HEARTOFAL1ON** [comment]
Just realized it could be because I am have enabled and I am using 2FA for my GitHub account. Let me try removing and see if SourceTree allows me to push a branch to my fork.

**Comment by YipZong** [comment]
Yea...my guess is that 2FA is a GitHub thing, so SourceTree does not support that?
EDIT: Additional setup needed. See 
[https://confluence.atlassian.com/sourcetreekb/two-factor-authentication-2fa-with-github-in-sourcetree-402033499.html](url)
and 
[https://help.github.com/articles/creating-a-personal-access-token-for-the-command-line/]()

**Comment by ghost** [comment]
@YezhongZ can it only work in `command line`? Btw, I tink something is wrong with your URLs (it redirects somewhere else than actually intended)

Anyway for now I will just disable 2FA on my GitHub account

**Comment by azhikai** [comment]
https://confluence.atlassian.com/sourcetreekb/two-factor-authentication-2fa-with-github-in-sourcetree-402033499.html

Try again. It works on both CLI and on SourceTree. You just need to login using the generated token rather than your password. Please store the token somewhere safe as I don't think you can retrieve it back from GitHub without regenerating a new one.

**Comment by ghost** [comment]
@AZhiKai perhaps tomorrow or over the weekend I'll try to configure it successfully :)
