### ISSUE TITLE
Should the assignee for a duplicate issue be the same person?

### ISSUE THREAD

**Issue by ghost** [nus-cs2103-AY1819S1/forum#201]
This is disregarding typo/grammar bugs but referring mainly to a functionality or a documentation bug.

Thank you!

By the way, I mean if it should _preferably_ be the same assignee.

**Comment by damithc** [comment]
I guess Yes, if you are claiming it to be duplicate :-p

**Comment by ghost** [comment]
Not really, the original issue already had an assignee. But as our group trawled through the issues, we realized another issue could be marked as a duplicate of that particular issue.

So what we did was to mark the duplicate issue as, well, a duplicate, but it doesn't have any assignee currently.

**Comment by azhikai** [comment]
I would just assign it to whoever is responsible for that issue, duplicate or not. Because there's also a chance that whatever you mark as `duplicate` will be rejected. If that's the case, and if there's no assignee, the whole team gets penalized.

**Comment by ghost** [comment]
@AZhiKai Currently the ~unspoken way~ of going about the issues is that we self-assign ourselves if the particular person who wants to take responsibility feels there is a need for them to so. :X

But yeah, will keep that into mind!

Thank you 😃 

EDIT: Not really "unspoken way" _per se_, but more like a "tacit agreement"

**Comment by ghost** [comment]
Also, just to clarify, if I assigned myself for the original, and I found duplicates of the same bug (or a teammate informed me about the existence of (a) duplicate(s), I would also assign myself as it is a matter of responsibility :)
