### ISSUE TITLE
Clarification on missing information from UserGuide

### ISSUE THREAD

**Issue by pengnam** [nus-cs2103-AY1819S1/forum#205]
![image](https://user-images.githubusercontent.com/28092058/48755378-04a3da80-ecd0-11e8-942d-31db471f9eb4.png)

The PE guidelines specified that missing information from the UserGuide is defined as a bug.

![image](https://user-images.githubusercontent.com/28092058/48755340-e807a280-eccf-11e8-9e8a-741ce226bc26.png)

![image](https://user-images.githubusercontent.com/28092058/48755864-d2937800-ecd1-11e8-8234-991ced5294e6.png)

My group received this bug report. 

We included every negative use case for every command but did not include this negative use case. It is also an unlikely negative use case as the product is a task manager. We thought the error message is self-explanatory. Is this an example of missing information?

**Comment by damithc** [comment]
It is fine if the error message is self-explanatory. It's not good to specify every nitty-gritty detail in the user guide either.

**Comment by pengnam** [comment]
Thank you!
