### ISSUE TITLE
Different bugs in 1 report yet receive multiple response label message from bot.

### ISSUE THREAD

**Issue by jjlee050** [nus-cs2103-AY1819S1/forum#206]
https://github.com/nus-cs2103-AY1819S1/pe-results/issues/308

I assigned 2 responses label to the issue as above because the bug report indicate 2 different bugs. However, I received this comment from the 2103 bot as below.

![screenshot 2018-11-20 at 23 42 20](https://user-images.githubusercontent.com/5901764/48784607-f9779b80-ed1d-11e8-8205-a69b1459af65.png)

Pls advice on how should I handle this. Should i ignore or just put 1 response label instead.

**Comment by jackedelic** [comment]
I think you can either response.Accept or response.IssueUnclear but not both.

**Comment by damithc** [comment]
Ignore the unclear bug. The reporter should not have put multiple bugs in the same issue.

**Comment by HEARTOFAL1ON** [comment]
Hijack a bit!

Bug report below also seemed to report on multiple bugs.

![image](https://user-images.githubusercontent.com/35895966/48819624-de437500-ed8b-11e8-97c7-ce5b28118a2f.png)

But yeah, they are documentation bugs.

**Comment by jjlee050** [comment]
Well, I just ignore the unclear bug then. Anyway, thanks for the advice.
