### ISSUE TITLE
Encountering a failure of a test during setting up addressbook-level4

### ISSUE THREAD

**Issue by hrxiong** [nus-cs2103-AY1819S1/forum#21]
I set up the addressbook-level4 according to the introduction of developer guide.
But i encountered a failure of the test during "run all tests".
And it's the only one that failed.
the image below is a screenshot of my intelliJ.
![image](https://user-images.githubusercontent.com/33370391/45197044-c9c60500-b291-11e8-8d86-a7a69dfee9dd.png)

**Comment by azhikai** [comment]
Can confirm that this is the only test case failing.

**Comment by damithc** [comment]
There is a new commit in the upstream repo. See if that fixes this problem.

**Comment by azhikai** [comment]
@damithc Can confirm that the new commit fixed the issue. Thanks!

**Comment by damithc** [comment]
Great. Thanks to the @se-edu/devs for the quick fix.
