### ISSUE TITLE
Black/White/Grey-box Testing 

### ISSUE THREAD

**Issue by jeffkwoh** [nus-cs2103-AY1819S1/forum#212]
Following the question in the mock test: 
Grey-box testing uses **some** knowledge of the SUT specification and **full** knowledge of its implementation. (the given answer is false)

I would like to check if these three statements are true:
1. Black-box testing uses **full** knowledge of the SUT specification and **no** knowledge of its implementation. 
2. White-box testing uses **no** knowledge of the SUT specification and **full** knowledge of its implementation. 
3. Grey-box testing uses **some** knowledge of the SUT specification and **some** knowledge of its implementation. (the given answer is false)

Here's the relevant portion of the textbook with regards to the various techniques:
![image](https://user-images.githubusercontent.com/23180853/49369487-79ddc980-f72c-11e8-83a6-48c1b54d1fec.png)

Any input would be appreciated, thanks so much for all your help in advance!

**Comment by damithc** [comment]
All three types of test case design require full knowledge of SUT specification i.e., how the SUT is _supposed_ to behave.  The tree differs on how much knowledge of the implementation is used in the test case design.

**Comment by jeffkwoh** [comment]
I see, thanks Prof @damithc !
