### ISSUE TITLE
Is the Logic class using the facade pattern?

### ISSUE THREAD

**Issue by jeffkwoh** [nus-cs2103-AY1819S1/forum#217]
Hi! Would I be able to ask a clarification for the facade class?

![image](https://user-images.githubusercontent.com/23180853/49485748-faa8dc80-f876-11e8-996a-62d07200a7c8.png)

Would the above be a facade class, seeing that the logic manager implementing it (transitively) has navigability to other classes via associations/dependencies?

![image](https://user-images.githubusercontent.com/23180853/49485780-18764180-f877-11e8-8eee-7c4d8fac50af.png)

Or would a facade pattern only apply to a class that has direct association to all of the classes within?

Thanks so much!

**Comment by aaditkamat** [comment]
Facade pattern involves using interface(s) as an intermediary between clients and the underlying classes in the component. I think Logic interface can be considered as a facade even though it does not have direct association to all of the classes because the client interacts with the component via the Logic interface which handles the interactions by making use of the transitive nature of the navigabilities that you have mentioned.

**Comment by damithc** [comment]
Facade pattern uses an object to act as the _interface_ to a component. The term _interface_ here does not refer to Java `interface`s. Facade pattern can be used with languages that don't even have an `interface` construct e.g., C++. The facade class may or may not implement an `interface`. I believe AB-4 Facade classes do implement a matching Java interface, but that is not a requirement of the pattern.

**Comment by damithc** [comment]
In the Logic component, `LogicManager` is the Facade class.

**Comment by jeffkwoh** [comment]
Ah, I see, thanks @aaditkamat  and Prof @damithc. Could I further confirm that as long as there's transitive navigabilities its a facade class? Not considering any violation of Law of Demeter

**Comment by damithc** [comment]
> Could I further confirm that as long as there's transitive navigabilities its a facade class?

Yes, that is a good indication, but the important thing is all clients interactions go through the Facade class.

**Comment by jeffkwoh** [comment]
Noted on this, Prof @damithc , thanks!
