### ISSUE TITLE
Suggestion for TEAMMATES student feedback page minor UI overflow issue

### ISSUE THREAD

**Issue by davidchoo12** [nus-cs2103-AY1819S1/forum#22]
Under question 5 of the student feedback page, each of the dropdown and table rows are displayed like this: (notice the overflow of the table on the right)
![image](https://user-images.githubusercontent.com/7817101/45229695-2a3c5d00-b2f9-11e8-9a55-a8b819e32bf0.png)

The html code is as follows
![image](https://user-images.githubusercontent.com/7817101/45231459-9c637080-b2fe-11e8-8942-fa982eb0cf4d.png)

Suggested simple changes:
- Set parent `<div>` classes: `col-sm-12 col-md-10 col-md-offset-1`
- Set children `<div>`s classes: `form-group`
- Remove "(Student):" text before the `<label>` tag
- Set the text of the default selected `<option>` to "Select a student" or something informative

![image](https://user-images.githubusercontent.com/7817101/45231428-83f35600-b2fe-11e8-9f43-8589a4e93e21.png)

Once changes are applied, it should look like the top one of the following image:
![image](https://user-images.githubusercontent.com/7817101/45231505-c026b680-b2fe-11e8-8473-e8b502d3dbb7.png)

Since I don't dare to touch the huge codebase of the TEAMMATES project and I don't know if this page is actually made by TEAMMATES or configured by the prof, I'm just gonna leave this here.

**Comment by damithc** [comment]
Yes, it is a TEAMMATES flaw. Thanks for reporting it @hidingmode Can you help report it at https://github.com/TEAMMATES/teammates/issues with the suggested solution?
