### ISSUE TITLE
Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.

### ISSUE THREAD

**Issue by Zackkh95** [nus-cs2103-AY1819S1/forum#29]
Hi everyone I have encountered this bug when setting up Addressbook Level 4 upon entering "gradlew processResources": 

Bug message:

Starting a Gradle Daemon, 1 incompatible and 8 stopped Daemons could not be reused, use --status for details

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.

Does anyone know how to resolve this?

Zach

**Comment by yamgent** [comment]
`addressbook-level4` is configured to use `4.8.1`, which is the default version used when running `gradlew`, so I am surprised that you got this error message (which seems to be implying that Gradle is running version `5.0.0` or greater).

Can you try running `./gradlew --version` and paste the output here, so that we can see what's going on?

**Comment by Zackkh95** [comment]
![gradle_version](https://user-images.githubusercontent.com/40956661/45730230-5cfe1500-bb85-11e8-84d8-9889f01a7403.PNG)


Error message(in case if you can't see pic):

C:\Users\Zackkh95\Documents\addressbook-level4>gradlew --version
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.codehaus.groovy.reflection.CachedClass (file:/C:/Users/Zackkh95/.gradle/wrapper/dists/gradle-4.8.1-bin/e8p42vx1m7a3mz9ydmjagn6w
n/gradle-4.8.1/lib/groovy-all-2.4.12.jar) to method java.lang.Object.finalize()
WARNING: Please consider reporting this to the maintainers of org.codehaus.groovy.reflection.CachedClass
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

------------------------------------------------------------
Gradle 4.8.1
------------------------------------------------------------

Build time:   2018-06-21 07:53:06 UTC
Revision:     0abdea078047b12df42e7750ccba34d69b516a22

Groovy:       2.4.12
Ant:          Apache Ant(TM) version 1.9.11 compiled on March 23 2018
JVM:          9.0.4 (Oracle Corporation 9.0.4+11)
OS:           Windows 8.1 6.3 amd64

**Comment by yamgent** [comment]
Maybe try running `./gradlew processResources` again? If not, re-clone the repository and go through the setup procedures again.

**Comment by Zackkh95** [comment]
Yeah. I've tried the above. I've even reinstalled Java JDK 9.0.4.

I'm still getting this warning:

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0. 

I'm pretty much at my wits end with this.

**Comment by damithc** [comment]
@Zackkh95 as spoken, you can ignore the warning and continue the development work if the warning doesn't affect anything else.

**Comment by damithc** [comment]
Closing because the issue seems to be resolved (or no longer applicable). Please reopen if not.
