### ISSUE TITLE
Error with setting up auto publishing of docs

### ISSUE THREAD

**Issue by ChooJeremy** [nus-cs2103-AY1819S1/forum#33]
Hi,

I have attempted to set up the auto publishing of docs for my team's repository at https://github.com/CS2103-AY1819S1-F10-1/main 
My commits have passed the gradle tests:
![gradle1](https://user-images.githubusercontent.com/4904988/45860282-ef2a3700-bd98-11e8-9607-000174c67aff.png)
but the website link for that repository [still returns 404](https://cs2103-ay1819s1-f10-1.github.com/main).

I have set up the environment variables:
![image](https://user-images.githubusercontent.com/4904988/45860350-492afc80-bd99-11e8-8089-8ae224493817.png)
acquired from my alt account [bugfreeSpice](https://github.com/bugfreeSpice), who has been given admin access to the repository.

The gradle build log can be found [here](https://gist.github.com/ChooJeremy/25f30a1ec5131786d6f779d85982e842)

**Comment by azhikai** [comment]
Wrong URL. 
It should be **.io** i.e. https://cs2103-ay1819s1-f10-1.github.io/main/

**Comment by damithc** [comment]
@ChooJeremy good job describing the problem in detail (which helped to locate the problem quickly) and Kudos to @AZhiKai for the quick response.

@ChooJeremy please close the issue if the problem is resolved.

**Comment by ChooJeremy** [comment]
Thanks for the help! My mistake in mistaking that the URL followed github.com,
