### ISSUE TITLE
 ! [remote rejected] HEAD -> gh-pages (permission denied) error: failed to push some refs to 'https://github.com/USERNAME/main.git' Script failed with status 1 failed to deploy

### ISSUE THREAD

**Issue by spencertan96** [nus-cs2103-AY1819S1/forum#34]
I've been trying to set up auto-publishing of docs, but it seems that my Travis CI build has errors after doing the suggested change in the instructions, namely, removing the codacy badge from README. Since then, my other commits have also resulted in failed builds in Travis CI and I'm not sure how to fix it.

I've tried googling for the error shown in my first build error, when I removed the codacy badge but I can't seem to find the exact error I'm running into. I've attached my build history, code change to remove the codacy badge and the error message for the build after removing the codacy badge. Would greatly appreciate help with this!
![error page 1](https://user-images.githubusercontent.com/42445828/45867504-34a92d00-bdb6-11e8-99d2-9cd9719a39c5.png)
![error page 2](https://user-images.githubusercontent.com/42445828/45867513-3a067780-bdb6-11e8-8973-176e0ed482ae.png)

**Comment by ghost** [comment]
Could it be because you are trying to push to the `gh-pages` branch??

**Comment by damithc** [comment]
Make sure the GitHub token you used is from an account that has permission to push to the repo you are trying to set up.
BTW, it looks like you are trying to set up auto-publishing to your own fork; there is no need to set up auto-publishing to your fork. It's enough it is set up for the team repo.

**Comment by ghost** [comment]
My bad. Yes I think I also only set up auto-publishing for the team repo  :)
> BTW, it looks like you are trying to set up auto-publishing to your own fork; there is no need to set up auto-publishing to your fork. It's enough it is set up for the team repo.

**Comment by spencertan96** [comment]
> Could it be because you are trying to push to the `gh-pages` branch??

Do you mean 
![image](https://user-images.githubusercontent.com/42445828/46013201-216fc780-c0fe-11e8-9468-f91a9f77ac0d.png)?

Should it be another option?

**Comment by spencertan96** [comment]
> Make sure the GitHub token you used is from an account that has permission to push to the repo you are trying to set up.
> BTW, it looks like you are trying to set up auto-publishing to your own fork; there is no need to set up auto-publishing to your fork. It's enough it is set up for the team repo.

I used my own account to generate the token, which I'm pretty sure has permission to push to the repo. I believe it's auto-publishing to the team repo?? I didn't touch anything of my fork.

**Comment by damithc** [comment]
Based on the error message you posted, Travis is trying to push to your own fork, not the team fork.
![image](https://user-images.githubusercontent.com/1673303/46014577-60a01780-c102-11e8-9b21-c3c99c28dc8b.png) Perhaps you mixed up setting up Travis for your team fork with setting up Travis for your own fork? Both of those repos will be available on Travis and I believe you are presented with your own fork by default when you log in.

**Comment by spencertan96** [comment]
Alright I think I fixed that error, but now there's another one 
![image](https://user-images.githubusercontent.com/42445828/46057966-08612800-c18b-11e8-9105-1525c2717e97.png)
Is it because I didn't set up coverage reporting for my team with Coveralls?

**Comment by damithc** [comment]
As this is a separate problem, post it as a new issue with a suitable title and a complete description so that someone from the dev team (or a classmate) can help you.

**Comment by damithc** [comment]
@spencertan96 please close this issue if no longer applicable.
