### ISSUE TITLE
I get this error when running MainApp. Any idea how to fix this error?

### ISSUE THREAD

**Issue by jjlee050** [nus-cs2103-AY1819S1/forum#35]
<img width="900" alt="screen shot 2018-09-21 at 16 40 10" src="https://user-images.githubusercontent.com/5901764/45871652-98d0ee80-bdc0-11e8-91e3-4f771f04bb7f.png">

**Comment by damithc** [comment]
Is this happening for the original AB-4 code or for a version that has been modified by you/your team?

**Comment by jjlee050** [comment]
Original. No modification have been made to any of the code.

**Comment by yamgent** [comment]
The call stack in such error messages usually provides invaluable information in nailing down the source of the problem (Tip: Text highlighted in orange are files specific to your project, you can click the name to jump to that file).

In particular, this line may be of interest to you:

```
at seedu.address.ui.UiManager.start(UiManager.java:52)
```

Line 52 of `UiManager.java` will try to load an image from `/images/address_book_32.png`.

Check that you have not accidentally removed that image on your local machine (you should find the file in `src/main/resources/images/address_book_32.png`).

**Comment by jjlee050** [comment]
nope. i did not remove or touch the image. has it got something to do with intellj idea update?

**Comment by ghost** [comment]
Actually this issue happened before, but rarely. Worst come to worst, may need to delete the local repo and reclone it. But hey, better not to just take my advice word for word first!

I suggested that since you said that there were no modifications to the clone of the original.

And yes what @yamgent (one of the upstream developers) said makes sense. Yes, the call stack is a very good place to look at if there are error messages :)

**Comment by yamgent** [comment]
> has it got something to do with intellj idea update?

That is unlikely, but it is worth a try to re-import the project and see if it fixes the error.

Also, if you ran the application through the IntelliJ's green play button, have you tried running it through Gradle instead to see if the same error occurs? (i.e. `./gradlew run`)

**Comment by jjlee050** [comment]
Thanks @yamgent and @HEARTOFAL1ON. I try reimporting the project and the error is fixed.
