### ISSUE TITLE
Request to use library: Simple Java Mail

### ISSUE THREAD

**Issue by pixelky** [nus-cs2103-AY1819S1/forum#36]
Dear Prof Damith,

Is it okay for us to use [Simple Java Mail](http://www.simplejavamail.org/#/about)? 

We are hoping to use it to write EML files and also to send emails.

Thank you.

**Comment by damithc** [comment]
The library is approved. Make a note of the following though:
![image](https://user-images.githubusercontent.com/1673303/45916731-8a0c3980-be9d-11e8-9f71-dbe8fa56c1a9.png)
