### ISSUE TITLE
Does working on ABL3 count towards project grade/marks?

### ISSUE THREAD

**Issue by ghost** [nus-cs2103-AY1819S1/forum#38]
For v1.1 milestone.

For example, like minor tweaks to existing Java code e.g. "total" or "sort" command

**Comment by damithc** [comment]
No, as it doesn't contribute to v1.1 directly.

**Comment by ghost** [comment]
Oh I see :(

I guess it's a fallback to practise temporarily before doing some modifications to ABL4 though :)

Can I then ask something else? Because I remember hearing that the group project can fall back to ABL3 or even ABL2 if ABL4 really seems too "hard", and this was mentioned during lecture. Of course, the best is to still dedicate ABL4 as the `main` repository of our `teamorg`

**Comment by damithc** [comment]
yes, you can fall back on a lower level AB, but after v1.1
