### ISSUE TITLE
Question on code standard (import statements)

### ISSUE THREAD

**Issue by anubh-v** [nus-cs2103-AY1819S1/forum#41]
Hi all,
I wish to clarify the stance on whitespace in blocks import statements.

From our module standard, it seems that we should add 1 blank line between imports from different packages (as seen in the picture below) - **but this is not explicitly mentioned** 

![image](https://user-images.githubusercontent.com/35621759/45942060-84386480-c013-11e8-80e5-521ddd9543e7.png)

However, the Google Java style guide (which we are also using) says:
![image](https://user-images.githubusercontent.com/35621759/45942118-bfd32e80-c013-11e8-8dad-bf62bb418159.png)

Do we just follow the example in our module standard?

Thanks

**Comment by amrut-prabhu** [comment]
Yep, follow the module standard.
The second bullet point under [1.4.1](https://github.com/nus-cs2103-AY1819S1/addressbook-level4/blob/master/docs/DeveloperGuide.adoc#configurations-to-do-before-writing-code) in the AB4 Developer Guide shows you explicitly what the order should be for the codebase used for your project.

**Comment by damithc** [comment]
In general, when the coding standard does not mention something, you can try to be consistent with the existing code in the code base. If the code base has differing styles, follow the style followed by the code nearby.

**Comment by anubh-v** [comment]
Noted, thanks Amrut and Prof

**Comment by damithc** [comment]
Closing because no longer actively discussed. Please reopen if there are further inputs.
