### ISSUE TITLE
Event driven architecture style VS Transaction processing architecture style

### ISSUE THREAD

**Issue by kohchihao** [nus-cs2103-AY1819S1/forum#43]
Hi everyone, I just want to check what is the differences between these 
`Event driven architecture style` and `Transaction processing architecture style`

Personally to me, they look exactly the same. 

Each event can have multiple transactions?
Each transaction can have multiple events?

**Comment by damithc** [comment]
Yes, they look similar, especially the diagram. One main difference: _transaction_ vs _event_. 
* A _transaction_ (e.g., a request to delete a file) is created (more like _requested_) in one part of software which is then dispatched to another part of the software to process. In some sense, the CLI execution mechanism of AB-4 has elements of this style. 
* An _event_ is something that happened e.g., user clicked a button, _raised_ by one part of the software, which is detected by a central mechanism, which notifies other parts of the software that are interested in that event. Those parts, when notified, can react to the event in any way they choose to.

**Comment by damithc** [comment]
Closing because no longer actively discussed. Please reopen if there are further inputs.

**Comment by monmanuela** [comment]
> Yes, they look similar, especially the diagram. One main difference: _transaction_ vs _event_.
> 
> * A _transaction_ (e.g., a request to delete a file) is created (more like _requested_) in one part of software which is then dispatched to another part of the software to process. In some sense, the CLI execution mechanism of AB-4 has elements of this style.
> * An _event_ is something that happened e.g., user clicked a button, _raised_ by one part of the software, which is detected by a central mechanism, which notifies other parts of the software that are interested in that event. Those parts, when notified, can react to the event in any way they choose to.

Since _transaction_ and _event_ are inherently different, is it possible that a software has both the architecture of transaction and event-driven at the same time? Or are they mutually exclusive?

**Comment by damithc** [comment]
> Since _transaction_ and _event_ are inherently different, is it possible that a software has both the architecture of transaction and event-driven at the same time? Or are they mutually exclusive?

Possible. All architecture styles can be combined with others.
