### ISSUE TITLE
The method "...()" has an NPath complexity of ...

### ISSUE THREAD

**Issue by ghost** [nus-cs2103-AY1819S1/forum#45]
Anyone able to help us with [this](https://github.com/CS2103-AY1819S1-F11-1/main/pull/47#issuecomment-424615200)?

![image](https://user-images.githubusercontent.com/35895966/46064583-53d30080-c1a2-11e8-8e18-25c7035a24df.png)

Something wrong that causes the Codacy test to fail for our [PR](https://github.com/CS2103-AY1819S1-F11-1/main/pull/47) :(

**Comment by damithc** [comment]
A codacy bug? Anyway, codacy warnings can be ignored on a case-by-case basis. NPath is a complexity measure but it is not in the syllabus; can ignore if you can't figure out any obvious problem with the flagged code.

**Comment by ghost** [comment]
Thanks Prof!

> codacy warnings can be ignored on a case-by-case basis

so does this mean it is okay to merge the PR?
