### ISSUE TITLE
Cannot open MainWindow.fxml in SceneBuilder

### ISSUE THREAD

**Issue by rebstan97** [nus-cs2103-AY1819S1/forum#48]
![image](https://user-images.githubusercontent.com/28558133/46120809-a7495b00-c243-11e8-80f2-82f57e496a14.png)

**Comment by yamgent** [comment]
Please post the content of your `MainWindow.fxml`.

**Comment by rebstan97** [comment]
`<?xml version="1.0" encoding="UTF-8"?>

<?import java.net.URL?>
<?import javafx.geometry.Insets?>
<?import javafx.scene.Scene?>
<?import javafx.scene.control.Menu?>
<?import javafx.scene.control.MenuBar?>
<?import javafx.scene.control.MenuItem?>
<?import javafx.scene.control.SplitPane?>
<?import javafx.scene.image.Image?>
<?import javafx.scene.layout.StackPane?>
<?import javafx.scene.layout.VBox?>

<fx:root type="javafx.stage.Stage" xmlns="http://javafx.com/javafx/8" xmlns:fx="http://javafx.com/fxml/1"
         minWidth="450" minHeight="600" onCloseRequest="#handleExit">
  <icons>
    <Image url="@/images/address_book_32.png" />
  </icons>
  <scene>
    <Scene>
      <stylesheets>
        <URL value="@DarkTheme.css" />
        <URL value="@Extensions.css" />
      </stylesheets>

      <VBox>
        <MenuBar fx:id="menuBar" VBox.vgrow="NEVER">
          <Menu mnemonicParsing="false" text="File">
            <MenuItem mnemonicParsing="false" onAction="#handleExit" text="Exit" />
          </Menu>
          <Menu mnemonicParsing="false" text="Help">
            <MenuItem fx:id="helpMenuItem" mnemonicParsing="false" onAction="#handleHelp" text="Help" />
          </Menu>
        </MenuBar>

        <StackPane VBox.vgrow="NEVER" fx:id="commandBoxPlaceholder" styleClass="pane-with-border">
          <padding>
            <Insets top="5" right="10" bottom="5" left="10" />
          </padding>
        </StackPane>

        <StackPane VBox.vgrow="NEVER" fx:id="resultDisplayPlaceholder" styleClass="pane-with-border"
                   minHeight="100" prefHeight="100" maxHeight="100">
          <padding>
            <Insets top="5" right="10" bottom="5" left="10" />
          </padding>
        </StackPane>

        <SplitPane id="splitPane" fx:id="splitPane" dividerPositions="0.4" VBox.vgrow="ALWAYS">
          <VBox fx:id="personList" minWidth="340" prefWidth="340" SplitPane.resizableWithParent="false">
            <padding>
              <Insets top="10" right="10" bottom="10" left="10" />
            </padding>
            <StackPane fx:id="personListPanelPlaceholder" VBox.vgrow="ALWAYS"/>
          </VBox>

          <StackPane fx:id="browserPlaceholder" prefWidth="340" >
            <padding>
              <Insets top="10" right="10" bottom="10" left="10" />
            </padding>
          </StackPane>
        </SplitPane>

        <StackPane fx:id="statusbarPlaceholder" VBox.vgrow="NEVER" />
      </VBox>
    </Scene>
  </scene>
</fx:root>
`

**Comment by rebstan97** [comment]
Code wasn't changed from AB4

```
<?xml version="1.0" encoding="UTF-8"?>

<?import java.net.URL?>
<?import javafx.geometry.Insets?>
<?import javafx.scene.Scene?>
<?import javafx.scene.control.Menu?>
<?import javafx.scene.control.MenuBar?>
<?import javafx.scene.control.MenuItem?>
<?import javafx.scene.control.SplitPane?>
<?import javafx.scene.image.Image?>
<?import javafx.scene.layout.StackPane?>
<?import javafx.scene.layout.VBox?>

<fx:root type="javafx.stage.Stage" xmlns="http://javafx.com/javafx/8" xmlns:fx="http://javafx.com/fxml/1"
         minWidth="450" minHeight="600" onCloseRequest="#handleExit">
  <icons>
    <Image url="@/images/address_book_32.png" />
  </icons>
  <scene>
    <Scene>
      <stylesheets>
        <URL value="@DarkTheme.css" />
        <URL value="@Extensions.css" />
      </stylesheets>

      <VBox>
        <MenuBar fx:id="menuBar" VBox.vgrow="NEVER">
          <Menu mnemonicParsing="false" text="File">
            <MenuItem mnemonicParsing="false" onAction="#handleExit" text="Exit" />
          </Menu>
          <Menu mnemonicParsing="false" text="Help">
            <MenuItem fx:id="helpMenuItem" mnemonicParsing="false" onAction="#handleHelp" text="Help" />
          </Menu>
        </MenuBar>

        <StackPane VBox.vgrow="NEVER" fx:id="commandBoxPlaceholder" styleClass="pane-with-border">
          <padding>
            <Insets top="5" right="10" bottom="5" left="10" />
          </padding>
        </StackPane>

        <StackPane VBox.vgrow="NEVER" fx:id="resultDisplayPlaceholder" styleClass="pane-with-border"
                   minHeight="100" prefHeight="100" maxHeight="100">
          <padding>
            <Insets top="5" right="10" bottom="5" left="10" />
          </padding>
        </StackPane>

        <SplitPane id="splitPane" fx:id="splitPane" dividerPositions="0.4" VBox.vgrow="ALWAYS">
          <VBox fx:id="personList" minWidth="340" prefWidth="340" SplitPane.resizableWithParent="false">
            <padding>
              <Insets top="10" right="10" bottom="10" left="10" />
            </padding>
            <StackPane fx:id="personListPanelPlaceholder" VBox.vgrow="ALWAYS"/>
          </VBox>

          <StackPane fx:id="browserPlaceholder" prefWidth="340" >
            <padding>
              <Insets top="10" right="10" bottom="10" left="10" />
            </padding>
          </StackPane>
        </SplitPane>

        <StackPane fx:id="statusbarPlaceholder" VBox.vgrow="NEVER" />
      </VBox>
    </Scene>
  </scene>
</fx:root>
```

**Comment by pyokagan** [comment]
@rebstan97 

Unfortunately, support for Stage/Scene as the roots of FXML files was only added fairly recently (2 weeks ago) in Gluon SceneBuilder, and Gluon hasn't published a new version of SceneBuilder that contains that feature yet.

Instead, you can download a developmental snapshot from https://ci.appveyor.com/project/damithc/scenebuilder-1/build/3/artifacts , which should solve your problem.

**Comment by rebstan97** [comment]
@pyokagan 
Thank you!

**Comment by fzdy1914** [comment]
@pyokagan 
May I ask how to use the developmental snapshot?

**Comment by pyokagan** [comment]
It's a JAR file. Just double click to open it.

If that doesn't work, you can run it via the command line using:

```
java -jar NameOfJarFile.jar
```

**Comment by elroyhaw** [comment]
@pyokagan May I ask how can we see our changes to MainWindow.fxml using SceneBuilder since we can't really open our version and have to use the snapshot?

**Comment by pyokagan** [comment]
> May I ask how can we see our changes to MainWindow.fxml using SceneBuilder since we can't really open our version and have to use the snapshot?

`Preview` -> `Show preview in Window` as usual. I believe the JavaFX tutorial in the book already mentions that.

**Comment by elroyhaw** [comment]
@pyokagan I was referring to the changes we make on our project's MainWindow.fxml, since SceneBuilder is unable to show the content, previewing it will only show a window with the following: "Not a Node". The suggestion you gave above is to use the snapshot to open the original AB4's MainWindow.fxml on SceneBuilder, but can we make changes on this snapshot?

**Comment by pyokagan** [comment]
Yes

**Comment by elroyhaw** [comment]
@pyokagan Thank you!

**Comment by damithc** [comment]
Closing because the issue seems to be resolved. Please reopen if not.
