### ISSUE TITLE
Clarification on connecting to Google resources

### ISSUE THREAD

**Issue by chivent** [nus-cs2103-AY1819S1/forum#49]
Dear Prof Damith,

My team is developing a console app that performs batch operations on images, and we were thinking to provide a functionality allowing people to edit photos from Google Photos. 

Upon much research, I have found that connecting to a google account will be done via Google OAuth 2.0, and it requires for at least a one-time authentication via browser pop-up for every new login (connection to account). Authenticating via a webview or client login (username/password)
 has already been depreciated by Google.

So the eventual flow would be similar to: Trigger login in CLI app --> browser redirect where user authenticates --> User manually returns to CLI

May I ask if this would be allowed (since the app ideally needs no mouse interaction)? Or if there is any other way of authentication that I may be overlooking? 

Thanks.

**Comment by damithc** [comment]
Yes it is fine to take a short detour from CLI if there is no other way. Also note the following constraint:

![image](https://user-images.githubusercontent.com/1673303/46244411-35267100-c411-11e8-9a49-7417f7a88db9.png)

**Comment by chivent** [comment]
Noted, thank you for the prompt reply prof!

**Comment by chivent** [comment]
I forgot to clarify, does this mean that I'm free to use Google Photos Java API Client and its associated libraries? (Google+/Photos/OAuth Java Client Library, [netty framework dependency in gradle](https://netty.io/))

**Comment by damithc** [comment]
Yes, allowed. Use at your own risk though.

**Comment by damithc** [comment]
Closing because no longer actively discussed. Please reopen if there are further inputs.
