### ISSUE TITLE
What are the circumstances which calls for modifying teams?

### ISSUE THREAD

**Issue by ghost** [nus-cs2103-AY1819S1/forum#5]
![image](https://user-images.githubusercontent.com/35895966/44782546-24889e00-abba-11e8-88eb-b57b49f3815c.png)

As seen under Tutorial 3 of module website. Just curious :o 

Apologies in advance if this is a stupid question... :(

**Comment by damithc** [comment]
e.g., There are only 4 non-locals in the tutorial but 2 of them are in the same team. In this case we have to pull one of them out to enable all 4 teams to meet our team forming criteria.

**Comment by ghost** [comment]
Hi prof @damithc , understood!

My point in contention was about the last bullet point:

> Also note that we may modify teams when circumstances call for it. There is no avenue for you to object. Staying with your preferred team is not guaranteed

What I thought was that in the event that all the 4 bullet points have already been fulfilled, are there any other circumstances than can cause bullet point 5 to happen? However, I think that last bullet point was probably built upon the previous 4 bullet points, haha...

Perhaps, and also, when the project is already ongoing and a group is in the "thick of things", most probably there wouldn't be any more group modifications?

Anyway, I perfectly understand so far. I think this system is fair :)

**Comment by damithc** [comment]
@HEARTOFAL1ON We don't expect to modify the teams in the middle of the project :-)
