### ISSUE TITLE
Use of ternary operators

### ISSUE THREAD

**Issue by YuPeiHenry** [nus-cs2103-AY1819S1/forum#51]
I have some doubts on the use of ternary operators (the format was given). Sometimes `ternary` operators can be compact and easy to read, but when they need to span multiple lines, are they still preferred over `if/else` branching for assigning values? Also, should we standardize to use only `ternary` or `if/else` to do variable assignments? Thanks.

**Comment by azhikai** [comment]
I tend to use ternary operation when assigning value to variables, and if-else for everything else.

I think there's not much of a standard here, but using ternary to assign value results in much shorter code so I'd go with that.

**Comment by davidchoo12** [comment]
I think ternary should be used when you have a value to assign for both if and else cases.
Also, **don't** chain ternary operators (unless you're taking CS3233). For example,
`x = cond ? (cond2 ? a : b) : (cond3 ? c : d)`

**Comment by damithc** [comment]
The final decision can be made on a case-by-case basis i.e., use it if the author and the reviewers think the ternary operator results in better readability (or no loss of readability) in a specific situation. 
The general advice is to use it sparingly.

**Comment by YuPeiHenry** [comment]
I just considered the issue of using negations inside the predicate for the ternary operator. Should negations in ternary be avoided, or are justifiable when it improves readability of code?

**Comment by damithc** [comment]
> I just considered the issue of using negations inside the predicate for the ternary operator. Should negations in ternary be avoided, or are justifiable when it improves readability of code?

If the coding standard is silent on that, you can decide yourself. Yes, it should be fine as long as you think it improves readability.

**Comment by damithc** [comment]
Closing because no longer actively discussed. Please reopen if there are further inputs.
