### ISSUE TITLE
Expected 8 persons, actual 7 persons

### ISSUE THREAD

**Issue by russellry** [nus-cs2103-AY1819S1/forum#55]
Hi there, I seem to be having an issue with the Assertion Error located in:

main\src\test\java\seedu\address\storage\XmlAddressBookStorageTest.java

<img width="960" alt="assertionerror" src="https://user-images.githubusercontent.com/16576977/46326395-1271a380-c62f-11e8-843f-45216fb6c573.png">

I suspect its due to
readBack = xmlAddressBookStorage.readAddressBook().get(); //file path not specified

that it is not editing the readBack variable due to not being able to get the file path, as its not specified.

**Comment by russellry** [comment]
https://github.com/se-edu/addressbook-level4/pull/918/commits/3eb588bafdc5e5683080cfca655f24d60356d905#diff-0f3475b6d0e939f7e453933e83d733aa

I have edited my code accordingly to the one line bug fix as well!

**Comment by damithc** [comment]
Perhaps you can create a PR for your code and share the link here? It's not easy for someone to help without seeing your code.

**Comment by russellry** [comment]
https://github.com/nus-cs2103-AY1819S1/addressbook-level4/pull/74

Sorry, I didn't include the PR. Would this be sufficient?

**Comment by damithc** [comment]
> Sorry, I didn't include the PR. Would this be sufficient?

No, that is too much code for a good samaritan to go through. You need to isolate the offending code first.
* Either give a link to the commit that is causing this problem i.e., the commit before it does not have this problem, or, 
* give the link to a PR that you created against your team repo that hopefully doesn't contain a lot of code but it does contain the code that is causng the problem.

**Comment by russellry** [comment]
https://github.com/nus-cs2103-AY1819S1/addressbook-level4/blob/4fce81025c1193decc8201315d653213f69fe41f/src/test/java/seedu/address/storage/XmlAddressBookStorageTest.java

line 76-100 (Actually 95 - 98 only for the assertion failure...)

Sorry about that, will take note!

**Comment by damithc** [comment]
Well, that's where the test fails but that's not helpful to find _why_ the test fails :-p To find the reason for the failure, one needs to start from a point where the test was passing last, and look through all the changes you have done since then.
I assume you doing this work in a branch? If yes, can you push the branch to your fork, create a temp PR to your team repo (for that branch), and give the link here?

**Comment by russellry** [comment]
and 5 hours later........... I finally got it haha, apparently I had no idea that java test files were correlated to the main java files as well, so when I made changes to these main java files, obviously the tests had failed....

Valuable lesson indeed though, thanks again prof :)

**Comment by damithc** [comment]
Nice :-)
Closing the issue.
