### ISSUE TITLE
Running command ./gradlew clean headless guiTests fails

### ISSUE THREAD

**Issue by adamwth** [nus-cs2103-AY1819S1/forum#57]
![testfail](https://user-images.githubusercontent.com/10760116/46348638-327e8280-c682-11e8-9357-856755a7bc75.PNG)

I am encountering this error when I run the command `./gradlew clean headless guiTests`. However, running `./gradlew clean headless nonGuiTests` gives me build successful. Any idea as to what might be causing this?

**Comment by ghost** [comment]
For me I run `gradlew clean checkstyleMain checkstyleTest headless allTests asciidoctor`. It is the equivalent of how Travis CI runs the tests I believe.

I guess you can refer to [here](https://github.com/se-edu/addressbook-level4/blob/master/docs/UsingGradle.adoc)

Another quite useful website page is probably [this](https://f14-b4.netlify.com/usingtravis)

**Comment by adamwth** [comment]
`allTests` includes `guiTests`. I have narrowed down the source of the error to `guiTests`. Would appreciate specific help with regards to that.

**Comment by pyokagan** [comment]
Are you using the Windows Subsystem for Linux? I don't think GUI applications will work with that...

**Comment by damithc** [comment]
Closing because the issue seems to be resolved (or no longer applicable). Please reopen if not.
