### ISSUE TITLE
./config/travis/check-line-endings.sh produces error: prohibited \r\n ending, use \n instead

### ISSUE THREAD

**Issue by adamwth** [nus-cs2103-AY1819S1/forum#58]
![travis_check_line_ending_fails](https://user-images.githubusercontent.com/10760116/46397982-5d221700-c726-11e8-9d34-7509b80c9417.PNG)

When I run the command `./config/travis/run-checks.sh`, I end up with these errors. I have managed to narrow down the error to the `/config/travis/check-line-endings.sh` file that is causing these errors. 
I should not be getting these errors as I have already checked that my editor (IntelliJ) uses LF line endings (i.e. \n). If anyone has encountered this problem before, or knows how to fix it, your advice would be greatly appreciated.

**Comment by JasonChong96** [comment]
Have you tried opening the file on IntelliJ and checking if the bottom right of the screen shows CRLF instead of LF?

![image](https://user-images.githubusercontent.com/35889982/46399730-2dc1d900-c72b-11e8-9c2b-426c21d3bf91.png)

If CRLF is set then you can just click on it to change

**Comment by adamwth** [comment]
Hi Jason, thank you for your reply. Yes I have checked and it says LF.

I have solved this issue by simply doing `git add .`. It seems that this error occurs when running the check before adding any untracked files. Should I close this issue?

**Comment by ghost** [comment]
Just fyi because I'm curious and I love Googling StackOverFlow =P
https://stackoverflow.com/questions/15433188/r-n-r-n-what-is-the-difference-between-them

Sorry, the above has been marked as a duplicate and I believe [this](https://stackoverflow.com/questions/1761051/difference-between-n-and-r) thread has a better answer =D
