### ISSUE TITLE
"Content of this document cannot be displayed" for 2 .fxml files when opened in SceneBuilder

### ISSUE THREAD

**Issue by spencertan96** [nus-cs2103-AY1819S1/forum#59]
The two files are MainWindow.fxml and HelpWindow.fxml
![image](https://user-images.githubusercontent.com/42445828/46429825-f595b700-c779-11e8-924d-04f7f6ce874b.png)
![image](https://user-images.githubusercontent.com/42445828/46429841-fe868880-c779-11e8-8b25-abc4f0f67428.png)
The application still works fine though, and when I open the .fxml files in IntelliJ, I see the raw code.

**Comment by damithc** [comment]
See if this helps https://github.com/nus-cs2103-AY1819S1/forum/issues/48

**Comment by spencertan96** [comment]
Oh okay I can view it now thanks!

**Comment by damithc** [comment]
> Oh okay I can view it now thanks!

Great. please close this issue if resolved.
