### ISSUE TITLE
📣 Email from cs2103.bot regarding W3.8

### ISSUE THREAD

**Issue by damithc** [nus-cs2103-AY1819S1/forum#6]
For week 3, you should receive an email from `cs2103.bot@gmail.com` on the day of your tutorial, stating our Bot's observation about your work for LO `W3.8 Can work with a 1KLoC code base`.
* **If you did not receive such an email** by the time of your tutorial, please let us know by emailing `cs2103@comp.nus.edu.sg`.
* **If the Bot observation you received is incorrect**, please reply to that email explaining the error.

In both cases, we'll need more time to follow up on your emails. To save time, **we will not reply to those emails for now**, unless we need some info from you. In the meantime, we'll try to correct those errors (e.g., if detection failed due to wrong GitHub ID, pushing to a different branch than `master`, renaming your fork, ...). 

At some point -- probably in week 5, after the re-submission deadline for `W3.8` is over -- we'll be publishing the participation marks. At that point you can get back to us if you do not receive the correct number of marks for that LO. Until then, **please don't stress about it; we'll make sure you get the marks if you did the work one way or other**. Auto-detecting work is a new thing we are trying this semester; we need time to iron out the kinks in the system.

**Comment by ghost** [comment]
Hi, so does this mean the deadline for LO W3.8 is extended? Or is it only for those students who have problems due to the bot or something like that?

Anyways, I will still try my best to stick to my own deadline which is by today, 2359 hrs.

TIA, @damithc !

**Comment by damithc** [comment]
> Hi, so does this mean the deadline for LO W3.8 is extended?

We give an extension to those who couldn't get it done on time.

**Comment by HEARTOFAL1ON** [comment]
Hi prof, thank you! An extension but does it mean they have to do 2 enhancements to make up for it or something? :o

**Comment by HEARTOFAL1ON** [comment]
Anyhow, completing W3.8 earns 2 participation marks, but there are also other ways to earn the full possible 10 marks as mentioned before if I recall? :)

I see it as a personal challenge to finish it by 2359 hours tonight. And I am confident I will! :D

**Comment by HEARTOFAL1ON** [comment]
Yay I finished this LO! :)
