### ISSUE TITLE
Need help with renaming seedu.address package

### ISSUE THREAD

**Issue by rongjiecomputer** [nus-cs2103-AY1819S1/forum#61]
My group is modifying the AddressBook to a Module Planner, so `seedu.address` package name is not appropriate.

I used the IntelliJ refactoring feature to change all references of `seedu.address` to `seedu.planner`. PR is at https://github.com/CS2103-AY1819S1-T16-4/main/pull/41, but many UI related tests are failing. Most of them have ` guitests.guihandles.exceptions.NodeNotFoundException` thrown.

Has anyone experienced similar issue when renaming package?

**Comment by damithc** [comment]
You guys did a codebase-wide (not just java files, but also other source files) search of `seedu.address`?

**Comment by rongjiecomputer** [comment]
> You guys did a codebase-wide (not just java files, but also other source files) search of seedu.address?

Yes. `.adoc` and `.fxml` are updated by IntelliJ too.

**Comment by rongjiecomputer** [comment]
Found the root cause: IntelliJ went all the way to change *string constant* as well. I had to manually hunt down those edits and revert. All tests pass now. Sorry for the noise.

**Comment by davidchoo12** [comment]
@rongjiecomputer 
> Found the root cause: IntelliJ went all the way to change _string constant_ as well. I had to manually hunt down those edits and revert. All tests pass now. Sorry for the noise.

May I know what string constant is being changed? Which file?

**Comment by rongjiecomputer** [comment]
@hidingmode EDIT: See last *two* commits in https://github.com/CS2103-AY1819S1-T16-4/main/pull/41
