### ISSUE TITLE
Request to use library: JSoup 

### ISSUE THREAD

**Issue by russellry** [nus-cs2103-AY1819S1/forum#63]
"jsoup is a Java library for working with real-world HTML. It provides a very convenient API for extracting and manipulating data, using the best of DOM, CSS, and jquery-like methods."

Is this accepted and allowed?

We are querying the definition of words from dictionary.com, it will be saved on our offline text files which can be accessible without Internet, but I read through the other forum posts about testing in an offline environment that might render this function unstable because it relies on having an Internet connection.

There are a few workarounds ie downloading an entire dictionary for offline querying but we felt that it will be way slower and does not benefit the project scope.

**Comment by damithc** [comment]
No objections to using the library.
As to the need for Internet connection, use at your own risk. There will be WiFi at the testing session, but we cannot guarantee the quality of the connection.
