### ISSUE TITLE
Modifying checkstyle rules

### ISSUE THREAD

**Issue by tuesmiddt** [nus-cs2103-AY1819S1/forum#64]
Hi, will we be penalised for removing checkstyle rules? I'm specifically referring to `sortImportsInGroupAlphabetically`.

**Comment by damithc** [comment]
No. You are free to modify checkstyle rules as you wish. **But you will be penalized if your code violates the given coding standard.**

**Comment by damithc** [comment]
@tuesmiddt you can close this issue if your question has been answered.
