### ISSUE TITLE
Different author names in commits

### ISSUE THREAD

**Issue by jasonvank** [nus-cs2103-AY1819S1/forum#68]
I follow the instruction to set the global GitHub username and user email in week 1. The author in the commits has different names with the same address. 
![image](https://user-images.githubusercontent.com/23273384/46579137-42a9af80-ca3e-11e8-8a5e-d924b23618ce.png)
It also affects my other repositories, which show my name like this.
![image](https://user-images.githubusercontent.com/23273384/46579145-67058c00-ca3e-11e8-8198-c1bf6e58917d.png)

May I know why it likes that? How this module extracts the code to grade?

**Comment by jasonvank** [comment]
@eugenepeh

**Comment by eugenepeh** [comment]
> May I know why it likes that? 

@jasonvank it can be due several reasons:
1. If you use the inbuilt VCS functionality on the intellij, it may perform the commits using your login credential, which hence it appears as your github username.
2. You may have different configuration on other devices
3. When you perform a merge on GitHub, GitHub amend the commits using your personal information on GitHub.

Basically, the configurations you made earlier, is only a local configuration. It doesn't affect other devices/GitHub.

>How this module extracts the code to grade?

More information will be provided in week 8. Generally multiple author names are fine, as long as each of them is uniquely identifiable (there isn't another contributor who has the same name as you). 

Hope that answers your question.

Best regards,
Eugene

**Comment by damithc** [comment]
@jasonvank see #74

**Comment by damithc** [comment]
Closing because no longer actively discussed. Please reopen if there are further inputs.
