### ISSUE TITLE
Help on removing a tab from tabs at top of README generated by Travis

### ISSUE THREAD

**Issue by spencertan96** [nus-cs2103-AY1819S1/forum#71]
![image](https://user-images.githubusercontent.com/42445828/46607547-0193c700-cb34-11e8-9317-3e75106fa06c.png)
Title. I can't seem to find it or a reference to it in README.adoc. To clarify, I'm talking about this bar:
![image](https://user-images.githubusercontent.com/42445828/46607612-3011a200-cb34-11e8-9b05-9efd042540f0.png)
Thank you!

**Comment by jjlee050** [comment]
![screen shot 2018-10-08 at 19 57 59](https://user-images.githubusercontent.com/5901764/46607699-7d8e0f00-cb34-11e8-835c-0e077b114ecb.png)
You can try edit the settings from the build.gradle first. You can go to developer guide section 4 for more details on editing the web page.

**Comment by YipZong** [comment]
Hi. You might want to take a look at my commit here. https://github.com/CS2103-AY1819S1-F11-1/main/commit/e84319beb9d51e98a842b6e03e1633bdcaa38243
Not sure whether my method is correct or not, hopefully, it helps.

**Comment by azhikai** [comment]
Generally, removing the `site-seedu` attribute in the gradle file should be enough to not cause the navbar to be rendered.

But if you want to remove it entirely, then you can do what @YezhongZ and his team did.

**Comment by spencertan96** [comment]
Alright thank you all! It should work now!!
