### ISSUE TITLE
📣 Check if RepoSense has identified your code correctly

### ISSUE THREAD

**Issue by damithc** [nus-cs2103-AY1819S1/forum#74]
## RepoSense 

In previous semesters we asked students to annotate all their code using special `@@author` tags so that we can extract each student's code for grading. This semester, we are trying out a new tool  called RepoSense that is expected to **reduce the need for such tagging**, and also make it **easier for you to see (and learn from) code written by others**.

We are now beta testing RepoSense, and if all goes well, we hope to officially adopt it for extracting code written by you guys. It the trial does not go well, we can always fall back on the tool we used before.

![image](https://user-images.githubusercontent.com/1673303/46614291-0c585700-cb48-11e8-8cc2-db71ccfc2089.png)

Figure: RepoSense Report Features

### 1. View the current status of code authorship data:
 
* **The report generated by the tool (as at ~~08 Oct 2018~~ 15 Oct 2018) is now available at [Project Code Dashboard (BETA)](https://nus-cs2103-ay1819s1.github.io/cs2103-dashboard).** The feature that is most relevant to you is the _Code Panel_ (shown on the right side of the screenshot above). It shows the code attributed to a given author. You are welcome to play around with the [other features](https://github.com/reposense/RepoSense/blob/release/docs/UserGuide.md#interpreting-the-report) (they are still under development and will not be used for grading this semester). 
* Click on your name to load the code attributed to you (based on Git blame/log data) onto the code panel on the right. 
* If the code shown roughly matches the code you wrote, all is fine and there is nothing for you to do.

### 2. If the code does not match:

Here are the possible reasons for the code shown not to match the code you wrote:
* the git username in some of your commits does not match your GitHub username (perhaps you missed our instructions to set your Git username to match GitHub username earlier in the project, or GitHub did not honor your Git username for some reason)
* the actual authorship does not match the authorship determined by git blame/log e.g., another student touched your code after you wrote it, and Git log attributed the code to that student instead

In those cases,
* Install RepoSense (see the [Getting Started](https://github.com/reposense/RepoSense/blob/release/docs/UserGuide.md#getting-started) section of the RepoSense User Guide)
* Use the two methods described in the RepoSense User Guide section [Configuring a Repo to Provide Additional Data to RepoSense](https://github.com/reposense/RepoSense/blob/release/docs/UserGuide.md#configuring-a-repo-to-provide-additional-data-to-reposense) to provide additional data to the authorship analysis to make it more accurate. **Important: If you add a `config.json` file to your repo (as specified by one of the two methods), please use the [template json file given in the module website](https://nus-cs2103-ay1819s1.github.io/cs2103-website/admin/reposenseConfigTemplates.html).**

  * After you are satisified with the new results (i.e., results produced by running RepoSense locally), push the `config.json` file you added and/or the annotated code to your repo. We'll use that information the next time we run RepoSense. 
  * If you choose to annotate code, please annotate code chunks not smaller than a method. We do not grade code snippets smaller than a method.
* If you encounter any problem when doing the above or if you have questions, please post here in the forum.
* **Take your time with the above. It's fine as long as you do the above by week 10.**

**Comment by Meena567** [comment]
Hi, for @evanmok2401 and I, the commits are not being recorded but the code is being detected (we can see the red progress line below but not the triangles).

**Comment by damithc** [comment]
> Hi, for @evanmok2401 and I, the commits are not being recorded but the code is being detected (we can see the red progress line below but not the triangles).

Thanks @Meena567 We'll investigate.

**Comment by davidchoo12** [comment]
Is it only showing codes written on the master branch? We have multiple branches

**Comment by damithc** [comment]
> Is it only showing codes written on the master branch? We have multiple branches

Yes, it checks only the master branch. Even if you have multiple branches, they are going to be merged to the master branch periodically (at least once for each milestone), right?

**Comment by jjlee050** [comment]
do we need to put @@author for all of our codes in order for repo sense to detect codes that made by us?

**Comment by damithc** [comment]
> do we need to put @@author for all of our codes in order for repo sense to detect codes that made by us?

@jjlee050 Using `@@author` tags is a last resort you can use to override the code authorship determined by RepoSense (based on Git data).

**Comment by davidchoo12** [comment]
> Yes, it checks only the master branch. Even if you have multiple branches, they are going to be merged to the master branch periodically (at least once for each milestone), right?

Yes, so our contributions will only show up once we merge to master.
Also, since we are graded by our consistency in contribution, does it make sense to also consider contributions through issues and comments?

**Comment by damithc** [comment]
> Yes, so our contributions will only show up once we merge to master.
> Also, since we are graded by our consistency in contribution, does it make sense to also consider contributions through issues and comments?

For consistency, it's good enough if you contribute to each milestone. i.e., merge to master at least once per milestone. However, it may be better to merge to master more often so that other team members can receive your new code more often. If you merge all team member branches near the milestone, you are doing a kind of a mini big-bang integration, which has all the associated risks. For example, a code of one team member can cause merge conflicts in all other team member codes near the deadline.

**Comment by davidchoo12** [comment]
What if we are using another branch, lets say v1.2, to do the continuous merging and only near the end of the milestone then we merge v1.2 to master?

**Comment by damithc** [comment]
> What if we are using another branch, lets say v1.2, to do the continuous merging and only near the end of the milestone then we merge v1.2 to master?

Still fine, as long as the code is merged to master before the milestone deadline.

**Comment by azhikai** [comment]
Hi Prof @damithc, can I check with you how often is RepoSense run?

**Comment by damithc** [comment]
> Hi Prof @damithc, can I check with you how often is RepoSense run?

About once a week, most likely. But if you want to test something out, you can run it yourself for your repo.

**Comment by ChooJeremy** [comment]
We are currently attempting to fix the problem by adding a config file under _reposense/config.json. (CS2103-AY1819S1-F10-1/main#25) However, config.json is currently ignored by .gitIgnore inside the repository, do we force add it?

Additionally, part of the configuration file asks us to input the display name. Do we input the display names you have for us in your link above (i.e. JEREM...UN KA)?

Is there any solution for committed changes that are then changed by others later on (giving wrong attribution), or are we forced to use @@author tags?

**Comment by damithc** [comment]
> We are currently attempting to fix the problem by adding a config file under _reposense/config.json. ([CS2103-AY1819S1-F10-1/main#25](https://github.com/CS2103-AY1819S1-F10-1/main/issues/25)) However, config.json is currently ignored by .gitIgnore inside the repository, do we force add it?

You can modify the `.gitignore` file as necessary

> Additionally, part of the configuration file asks us to input the display name. Do we input the display names you have for us in your link above (i.e. JEREM...UN KA)?

You can use either the full name or the abbreviated name used in the original report.

> Is there any solution for committed changes that are then changed by others later on (giving wrong attribution), or are we forced to use @@author tags?

For those code segments you'll have to use `@@author` tags.

**Comment by russellry** [comment]
Hi prof, I was just wondering why my name appears twice in RepoSense.

![image](https://user-images.githubusercontent.com/16576977/46790490-a818db80-cd71-11e8-8837-b2c3c717d0ce.png)
28 & 29

**Comment by damithc** [comment]
> Hi prof, I was just wondering why my name appears twice in RepoSense.

Possibly because you used two Git usernames in your commits. @eugenepeh what do you think?

**Comment by damithc** [comment]
> Hi prof, I was just wondering why my name appears twice in RepoSense.

@RussellOng95 BTW, try adding a config.json as explained in the RepoSense user guide to customize the analysis further. In that file, you can specify all Git usernames you used so that RepoSense can  consolidate all of them under one author.

**Comment by eugenepeh** [comment]
> Possibly because you used two Git usernames in your commits. @eugenepeh what do you think?

@RussellOng95 , this is because you've not configure the [json config file](https://github.com/reposense/RepoSense/blob/release/docs/UserGuide.md#provide-data-using-a-json-config-file) in your repository.

By default, due to the lack of context, RepoSense do not know which group of `author names` belongs to the same author. Which is why, to improve the accuracy, we require the users to fill up the information in the configuration files.

**Comment by RussellOng95** [comment]
Hi there @eugenepeh and @damithc , I have did the suggested but unfortunately it does not show up correctly yet. Am I missing something here?

![image](https://user-images.githubusercontent.com/16576977/46819388-2c8d4d80-cdb6-11e8-968d-60684202a0c9.png)

**Comment by russellry** [comment]
thank you @eugenepeh and @damithc - the issue has been resolved :)

**Comment by damithc** [comment]
[Project Code Dashboard (BETA)](https://nus-cs2103-ay1819s1.github.io/cs2103-dashboard) has been updated. If you added a `config.json` to your repo (to provide additional data to RepoSense), please check if the new report reflects the config data you supplied.

**Comment by ghost** [comment]
> We are currently attempting to fix the problem by adding a config file under _reposense/config.json. ([CS2103-AY1819S1-F10-1/main#25](https://github.com/CS2103-AY1819S1-F10-1/main/issues/25)) However, config.json is currently ignored by .gitIgnore inside the repository, do we force add it?
> 
> Additionally, part of the configuration file asks us to input the display name. Do we input the display names you have for us in your link above (i.e. JEREM...UN KA)?
> 
> Is there any solution for committed changes that are then changed by others later on (giving wrong attribution), or are we forced to use @@author tags?

@ChooJeremy For me, what I did was that I just created the file `_reposense/config.json` on my teamorg's GitHub repo itself and created a PR

**Comment by ChengYuuu** [comment]
Hi all,

I faced the following problem:
When I clicked on my name for RepoSense, I can see all the changes I made. However, when i click on the graph which redirects to github, I get the following message :"No commits found for (username)" for some of the spikes on the graph.

**Comment by eugenepeh** [comment]
> Hi all,
> 
> I faced the following problem:
> When I clicked on my name for RepoSense, I can see all the changes I made. However, when i click on the graph which redirects to github, I get the following message :"No commits found for (username)" for some of the spikes on the graph.

![image](https://user-images.githubusercontent.com/19277206/46991917-6b1a6380-d13a-11e8-8b36-18095aa4919b.png)


Hi @ChengYuuu , it seems that some of your commits were not recognized by the GitHub (as shown in the above image). Thus, the link was not able filter and show the commit that was made by you on several specified dates. This is may be due to the commit was made without the GitHub authentication. 

Rest assured that RepoSense will still be able to retrieve your contribution, inregardless of the GitHub authentication. Hence the graph (ramp chart) will still shows up even though the link doesn't work on the GitHub's end.

**Comment by rongjiecomputer** [comment]
@ChengYuuu Github is unable to recognize that you are the author of the commit because the email of the commit is not in your Github account.

If you see this raw patch of one of your unrecognized commit (https://github.com/CS2103-AY1819S1-F11-1/main/commit/0fc7bcc39c98642ffae575df1de56b2b4ed868eb.patch), you can see that the email is `chengyu@Gohs-MacBook-Pro.local`. I think you need to configure your local git client to use proper email address used in Github account instead.

**Comment by ChengYuuu** [comment]
Thank you.
Just to clarify it isn't a requirement to configure our email right?

@eugenepeh is there any action I need to take? or I can just leave it at the current state? Thank you.

**Comment by damithc** [comment]
> Just to clarify it isn't a requirement to configure our email right?

It is not a module requirement (but recommended). 

> @eugenepeh is there any action I need to take? or I can just leave it at the current state? Thank you.

It is fine as long as the code panel shows your code. No further action required.

**Comment by rongjiecomputer** [comment]
Even if the module does not require it, it is still a good idea to use a proper email address in commit anyway because you will likely be using git for future work too (like contributing to open-source project).

You can see https://help.github.com/articles/setting-your-commit-email-address-in-git/ on how to set git to use correct email address.

**Comment by ChooJeremy** [comment]
> 
> 
> > We are currently attempting to fix the problem by adding a config file under _reposense/config.json. ([CS2103-AY1819S1-F10-1/main#25](https://github.com/CS2103-AY1819S1-F10-1/main/issues/25)) However, config.json is currently ignored by .gitIgnore inside the repository, do we force add it?
> > Additionally, part of the configuration file asks us to input the display name. Do we input the display names you have for us in your link above (i.e. JEREM...UN KA)?
> > Is there any solution for committed changes that are then changed by others later on (giving wrong attribution), or are we forced to use @@author tags?
> 
> @ChooJeremy For me, what I did was that I just created the file `_reposense/config.json` on my teamorg's GitHub repo itself and created a PR

@HEARTOFAL1ON 
Thanks for the tip. I ended up resolving it by adding an exception to the .gitIgnore file, since based on what I interpreted from the prof's reply was that he would prefer that the .gitIgnore file was modified instead.

**Comment by andlimey** [comment]
Hello I installed RepoSense already but it still does not reflect the commits I've made. What should I do?

**Comment by eugenepeh** [comment]
@andlimey , if RepoSense is not reflecting the commits you've made correctly, do try to setup the [json config file](https://github.com/reposense/RepoSense/blob/release/docs/UserGuide.md#provide-data-using-a-json-config-file) in your team repository.

**Comment by andlimey** [comment]
@eugenepeh I already set up a config.json in my local repo and ran RepoSense but my commits are still not reflected.

**Comment by eugenepeh** [comment]
Hi @andlimey , try to include all the `authorNames` name used by each student in the config.json.

To know whats all of your teammates' author name, try running RepoSense against your team's repo without a config.json, it should show all the authors name within that period.

E.g. 
`java -jar RepoSense.jar -repo <YOUR_TEAM_REPO_URL.git> -since 01/09/2018`

**Comment by damithc** [comment]
> @eugenepeh I already set up a config.json in my local repo and ran RepoSense but my commits are still not reflected.

@andlimey If it still doesn't work, you can share your config.json file here for us to have a look.

**Comment by andlimey** [comment]
[https://github.com/andlimey/main/blob/master/_reposense/config.json](url) Here is the config.json file I used

**Comment by eugenepeh** [comment]
> https://github.com/andlimey/main/blob/master/_reposense/config.json Here is the config.json file I used

Yes. As your config for all the authors' authorNames only contains the GitHub ID, it is not very useful. 
Do try out my previous suggestion earlier.

>To know whats all of your teammates' author name, try running RepoSense against your team's repo without a config.json, it should show all the authors name within that period.

**Comment by andlimey** [comment]
Ahh okay. Its showing the commits now. Thanks!

**Comment by andlimey** [comment]
@eugenepeh My name however is reflected as "DESKTOP-XXXXXXX\Andy". Is there a way to change it?

**Comment by eugenepeh** [comment]
>@eugenepeh My name however is reflected as "DESKTOP-XXXXXXX\Andy". Is there a way to change it?

You can simply use `git config --global user.name "John Doe"` to change your existing author name to something else.

However, this will not change the author names for your previous commits. It is recommended to include that name into the `authorNames` so that RepoSense can perform the analysis. If there is personal reason that you would not like to include it due to privacy issue, here's 2 solutions:

* perform the action stated in this [SO](https://stackoverflow.com/questions/3042437/how-to-change-the-commit-author-for-one-specific-commit), but I wouldn't recommend that as its would be quite tedious and may requires force push to the master.

* The other way is to make use of the [@@author](https://github.com/reposense/RepoSense/blob/release/docs/UserGuide.md#provide-data-using-author-tags) tag to mark your code contributions that RepoSense have left out.

**Comment by andlimey** [comment]
@eugenepeh Noted. Thanks!

**Comment by azhikai** [comment]
Hi @eugenepeh  and Prof @damithc, just want to point out that the JSON format provided here is wrong https://nus-cs2103-ay1819s1.github.io/cs2103-website/admin/reposenseConfigTemplates.html

There should be a comma separating each object as shown here https://github.com/reposense/RepoSense/blob/release/docs/UserGuide.md#configuring-a-repo-to-provide-additional-data-to-reposense

**Comment by damithc** [comment]
> Hi @eugenepeh and Prof @damithc, just want to point out that the JSON format provided here is wrong https://nus-cs2103-ay1819s1.github.io/cs2103-website/admin/reposenseConfigTemplates.html

Thanks @AZhiKai. ~~Will fix soon.~~ EDIT: Fixed

**Comment by junjiee** [comment]
my commits are not recorded

**Comment by neilish3re** [comment]
Hi Prof, despite following all the suggestions above,  Project Code Dashboard (BETA) reposense still doesnt detect my code.
When I run reposense locally, all my code is detected correctly. Even my group member could detect my code when she ran reposense on her computer as well
I even updated the config.json file to include my other possible authornames.

What else can I do?
