### ISSUE TITLE
What happens if we finish our feature early...?

### ISSUE THREAD

**Issue by ghost** [nus-cs2103-AY1819S1/forum#78]
Hi Prof et al.,

I would like to ask what happens if we finish our feature early? To be more specific, a particular student A feels confident about their feature and cannot think of or does not really feel there is a need to do more "enhancements" _per se_.

My ideas are as follows:

- It is still good to merge some PRs or push some code (at least do it weekly)
- Perhaps can implement more extensive testing by including as many tests as possible?
- Always be on the look-out for any Java Coding Standard violations constantly and correct them immediately or ASAP (rationale: good software engineering practice I guess? and helps one to better oneself as a software engineer?)
- Any other suggestions?

It is **highly possible** that perhaps some students "finish" their enhancement earlier too right, I guess?

**Comment by damithc** [comment]
We do consider the consistency of contribution when grading the project management aspect. Those who spread their contribution over the full period will get more marks than those who do it in a short burst.

**Comment by ghost** [comment]
Hi Prof, I do not really mean doing everything in a "short burst" per se. Perhaps there is always something about the feature to improve (even during the later weeks of the semester). Even if there isn't (much), I guess that pushing some **meaningful** code like suggested above could help the situation I guess?

I hope people are understanding what I am trying to say, haha~

Anyway, I was just asking the question(s) hypothetically :)
