### ISSUE TITLE
Travis building wrong organization commit inside AB4 PR 

### ISSUE THREAD

**Issue by kohchihao** [nus-cs2103-AY1819S1/forum#81]
Hi Prof, it seems like the PR in AB4 for our team `FoodZoom` seems like Travis is  compiling other team code instead of ours :O 

https://travis-ci.org/nus-cs2103-AY1819S1/addressbook-level4/builds/439910825?utm_source=github_status&utm_medium=notification

**Comment by damithc** [comment]
@kohchihao please give a link to your PR as well

**Comment by kohchihao** [comment]
https://github.com/nus-cs2103-AY1819S1/addressbook-level4/pull/8

**Comment by damithc** [comment]
If travis is building the wrong code (similar things have happened before), you can close the PR and open a new one to see if that works. Provide links from each PR to the other.

**Comment by kohchihao** [comment]
Problem fixed by opening new PR. Thanks @damithc
