### ISSUE TITLE
Anyone knows how to squash commits?

### ISSUE THREAD

**Issue by ghost** [nus-cs2103-AY1819S1/forum#82]
As per above.

I find its potential usefulness for our group project repo on GitHub because sometimes the commits can be quite numerous (and we can squash multiple commits into one)

**Comment by azhikai** [comment]
In sourcetree: https://www.atlassian.com/blog/sourcetree/interactive-rebase-sourcetree/amp

For terminal, look into `git rebase`.

Btw, practice precaution when it comes to squashing. Some scenarios I think squashing can apply is if you have row of commits that just fixes checkstyle issue, etc. You should not squash commits that are of independent unit of work (e.g. you squash 2 commits, one implements feature A, another implements feature B).

**Comment by ghost** [comment]
I see. Yes I do remember seeing somewhere (from module website/textbook etc) or hearing somewhere (like lecture) that we should only use SourceTree's `rebase` feature **with caution** and only if we know what we are doing.

And cool I see I see~ So squashing and rebasing commits are related to each other I guess?

**Comment by azhikai** [comment]
> And cool I see I see~ So squashing and rebasing commits are related to each other I guess?

In a way yes, you squash commits by using rebase.
