### ISSUE TITLE
Is SourceTree's "stash" function useful? How different from branching?

### ISSUE THREAD

**Issue by ghost** [nus-cs2103-AY1819S1/forum#83]
So some of us may have heard about `stash`ing before. Is there any potential usefulness for our project?

How is it different from `branch`ing too?

From my understanding, `stash`ing is somewhat similar to the data structure of stacks?

**Comment by azhikai** [comment]
You stash your uncommitted changes to achieve a clean working copy of your code (or matching the HEAD).

In our case, say if you want to switch to another branch to do another feature but you don't want to commit your files yet, then you can stash it first. In SourceTree, i don't think you are allowed to navigate to other branches if you have uncommitted changes in the current branch. Of course, you can then apply the stash to anywhere you want in the future. 

I would say stashing is way cleaner than making a branch called `backup` or something.

No, it's not related to stack. Think of stashing as just putting all your undone work into a box and keeping it in a safe place, then retrieving it at a later date when you want to continue on it.

**Comment by ghost** [comment]
I see. `Stash`ing is not done in a LIFO order, even though it looks and sounds very similar to stack.

Thank you for your reply! They are always insightful, interesting and knowledgeable :D

**Comment by azhikai** [comment]
> I see. `Stash`ing is not done in a LIFO order, even though it looks and sounds very similar to stack.
> 
> Thank you for your reply! They are always insightful, interesting and knowledgeable :D

Yes, it has no relation to LIFO/FIFO/Stack or any data structure, at least not to us as users (we don't need to know how stashing works behind-the-scene, for all we know they're really using stack!).

No problem. 👍
