### ISSUE TITLE
My team's GitHub page not showing the "logo" and "ui" image properly

### ISSUE THREAD

**Issue by ghost** [nus-cs2103-AY1819S1/forum#86]
Here is the link for out [GH page](https://cs2103-ay1819s1-f11-1.github.io/main/) and this is my team repo's [link](https://github.com/CS2103-AY1819S1-F11-1/main/)

It is supposed to show [`logo.png`](https://github.com/CS2103-AY1819S1-F11-1/main/blob/master/docs/images/logo.png) and [`Ui.png`](https://github.com/CS2103-AY1819S1-F11-1/main/blob/master/docs/images/Ui.png) but it is not showing properly:
![image](https://user-images.githubusercontent.com/35895966/46900906-99026c80-cedc-11e8-9fab-27a123536828.png)

We want the 2 images to show on our GH page as shown on our [`README.adoc`](https://github.com/CS2103-AY1819S1-F11-1/main/blob/master/README.adoc) below:
![image](https://user-images.githubusercontent.com/35895966/46900821-7c196980-cedb-11e8-914a-f68e5ef57c18.png)

Here's the [PR](https://github.com/CS2103-AY1819S1-F11-1/main/pull/72) one of us made.

Asking on behalf of my team :) A thousand thanks in advance~

Warmest Regards,
Dan

P.S. Could publishing our team site on Netlify perhaps help things out a bit? :)

**Comment by azhikai** [comment]
Your `README` seems wrong at:

```
ifdef::env-github[]
image::docs/images/logo.png[width="900"]
endif::[]

== Showcase

ifdef::env-github[]
image::docs/images/Ui.png[width="600"]
endif::[]
```

Notice the line `ifdef::env-github[]`? It means that the content or in this case, your images will only show if it's on GitHub (not GitHub page though, I was also quite surprised it didn't work). Your `image::<directory>` also seems wrong. 

The following is my group's README.
(`ifndef` means if not defined).
```
ifdef::env-github[]
image::docs/images/Ui.png[width="600"]
endif::[]

ifndef::env-github[]
image::images/Ui.png[width="600"]
endif::[]

```
