### ISSUE TITLE
What would you classify this "hypothetical scenario" as?

### ISSUE THREAD

**Issue by ghost** [nus-cs2103-AY1819S1/forum#88]
Suppose your group project passes all the necessary tests, be it locally (i.e. Gradle) or submitting the PR to our module's [ABL4](https://github.com/nus-cs2103-AY1819S1/addressbook-level4), [ABL3](https://github.com/nus-cs2103-AY1819S1/addressbook-level3) or [ABL2](https://github.com/nus-cs2103-AY1819S1/addressbook-level2) (depending on which one the group decides to do) and passing Travis (plus Netlify right?)

Is it then possible for the product to not function as per intended?

What I mean is that you want your product to implement "this, this and this..." and you have done all the necessary automated testing (regression tests, JUnit tests and etc...) both locally and remotely, but instead the product behaves in one or more ways as not intended (maybe it performs "that, that and that..." instead)

I'm guessing this is called a validation problem? (or I forget the correct term from the module website). A.K.A. I guess a bug (or bugs)?

In that respects, that is why validation testing (which we just learnt from yesterday's lecture) is very important in addition to also perform verification testing I suppose?

From my understanding and/or memory:
- User testing is a form of validation testing?
- Verification testing is more of the functional-side testing of the product?

Also, both validation testing and verification testing form the QA (quality assurance) of a software product?

**Comment by damithc** [comment]
yes, your understanding is correct @HEARTOFAL1ON
