### ISSUE TITLE
Question about authorship for code reuse within the project

### ISSUE THREAD

**Issue by jeffkwoh** [nus-cs2103-AY1819S1/forum#90]
Hi all,  with regards to the policy on code reuse: https://nus-cs2103-ay1819s1.github.io/cs2103-website/admin/appendixB-policies.html#policy-on-reuse 

How should we approach this when we're reusing code within the project. For example, if I were to implement test cases for a new command by referring to other test cases already written in AB4, is there a need to indicate code reuse. And if yes, how do we credit the reuse, do we credit the organization which hosts the AB4 code?

Thanks!

**Comment by damithc** [comment]
You can reuse code within AB4 without giving credit to the original authors.

**Comment by jeffkwoh** [comment]
Thanks so much for the quick reply Prof @damithc 

To clarify, would this mean

reuse wihtout attribution
```=Java
// @@author unsatisfiedpopcorn-reuse
/*javadocs*/
 public method()...
```
or

No mention of reuse
```=Java
// @@author unsatisfiedpopcorn
/*javadocs*/
 public method()...
```
Thank you so much!

**Comment by damithc** [comment]
We don't force you to use the first one if the code you are reusing is from AB-4. If you think your contribution to the code is really minor, you can go with the first option; otherwise, you can take the second option. We are OK with both options.

**Comment by jeffkwoh** [comment]
Thank you Prof @damithc, will do!
