### ISSUE TITLE
Change from XML to use SQLITE db

### ISSUE THREAD

**Issue by kohchihao** [nus-cs2103-AY1819S1/forum#98]
Hi Prof, 

Just checking if it is possible to use SQLite db instead of using XML as a db? Because our application requires some form of relational management. For example, `deliveryman` have many `orders`, our XML would be something like 

```
<orders> 
<food> </food>
<deliveryman> 23 </deliveryman>
<orders> 
```

Using XML is quite troublesome to propagate delete or changes.

**Comment by damithc** [comment]
We have a project constraint against using databases.
