### ISSUE TITLE
Question on documentation level required for UML sequence diagram

### ISSUE THREAD

**Issue by jeffkwoh** [nus-cs2103-AY1819S1/forum#99]
Hi all,

When attempting to draw my own sequence diagram for documentation, I realised that in AB4's documentation it looks like some portion of the sequence has been omitted.

![image](https://user-images.githubusercontent.com/23180853/47078570-2bd13d00-d236-11e8-8dc8-446d62d01027.png)
![image](https://user-images.githubusercontent.com/23180853/47078597-3b508600-d236-11e8-8c7b-4e1c29efeccd.png)
It appears that line 44 - 50 is not drawn, as well as the following switch case statements:
![image](https://user-images.githubusercontent.com/23180853/47078649-58855480-d236-11e8-8f3f-6f0a7a78d05c.png)

Is there any guideline to follow on teh level of detail we can omit from the diagram? Or do we draw it  based on the level of detail the developers need? 

Thanks!

**Comment by damithc** [comment]
> Or do we draw it based on the level of detail the developers need?

Yes, include just enough details to serve the purpose. For good measure, you can include a note such as `some unrelated details omitted`.

**Comment by jeffkwoh** [comment]
Understood, thank you Prof @damithc  !
